source/site-administrators/engine/engine-headers-based-authentication.rst

Update example listed in header.ftl

[master] Update example listed in header.ftl

---

source/site-administrators/engine/engine-crafter-profile-configuration.rst
source/system-administrators/profile/admin/guides/access_tokens.rst

Add notes to use site name for tenant in Engine Crafter Profile configuration

[master] Add notes to use site name for tenant in Engine Crafter Profile configuration

---

source/site-administrators/engine-configuration.rst
source/site-administrators/engine/proxy-configuration.rst
source/site-administrators/studio-configuration.rst

Add note to proxy config and move proxy config to engine in site configuration

[master] Add note to proxy config

---

source/site-administrators/engine-configuration.rst
source/site-administrators/engine/proxy-configuration.rst
source/site-administrators/studio-configuration.rst

Add note to proxy config and move proxy config to engine in site configuration

[3.1] Add note to proxy config

---

source/developers/projects/craftercms/index.rst
source/system-administrators/activities/backup-and-recovery.rst

Update backup location description

[master] Update backup location description

---

source/developers/projects/craftercms/index.rst
source/system-administrators/activities/backup-and-recovery.rst

Update backup location description

[3.1] Update backup location description

---

source/conf.py
source/index.rst
source/release-notes/3-0-27.rst
source/security/advisory.rst
source/security/crafter-cms-security.rst
source/security/index.rst
source/security/security-policies.rst

Update 3.0.27 release notes

---

source/acknowledgements/index.rst

Update OSS acknowledgements for 3.1.10

Update OSS acknowledgements for 3.1.10

---

source/developers/projects/deployer/api/monitoring/version.rst
source/developers/projects/engine/api/monitoring/version.rst
source/developers/projects/search/api/monitoring/version.rst
source/developers/projects/social/api/v3/monitoring/version.rst
source/getting-started/quick-start-guide.rst
source/system-administrators/activities/installing-and-verifying-prerequisites.rst
source/system-administrators/index.rst
source/system-administrators/requirements-supported-platforms.rst

Update Java version requirement

Update Java version requirement

---

source/system-administrators/upgrade/index.rst

Add blurb of ES automatic index settings when upgrading in the upgrading section of the docs #4068

[3.1] Add blurb of ES automatic index settings when upgrading #4068

---

source/system-administrators/upgrade/index.rst

Add blurb of ES automatic index settings when upgrading #4068

[master] Add blurb of ES automatic index settings when upgrading #4068

---

source/developers/projects/studio/api/site/create-site.rst

Update example in create site api

[master] Update example in create site api

---

source/developers/projects/studio/api/site/create-site.rst

Update example in create site API

[3.1] Update example in create site API

---

source/developers/projects/engine/api/index.rst

Update Engine API note for crafterSite

[master] Update Engine API note for crafterSite

---

source/developers/projects/engine/api/index.rst

Update Engine API note for using crafterSite

[3.1] Update Engine API note for using crafterSite

---

source/system-administrators/activities/authoring/authoring-env-performance-tuning.rst

Update ulimit and add description of limit.conf

[3.1] Update ulimit and add description of limit.conf

---

source/system-administrators/activities/authoring/authoring-env-performance-tuning.rst

Update ulimit and add description of limit.conf

[master] Update ulimit and add description of limit.conf

---

source/developers/projects/studio/api/site/get-sites-per-user.rst

Update the example for get-sites-per-user API

[3.1] Update the example for get-sites-per-user API

---

source/developers/projects/studio/api/site/get-sites-per-user.rst

Update example in get-sites-per-user API

[master] Update example in get-sites-per-user API

---

source/system-administrators/crafter-cli/add-environment.rst
source/system-administrators/crafter-cli/add-remote.rst
source/system-administrators/crafter-cli/crafter-cli-commands.rst
source/system-administrators/crafter-cli/create-site.rst
source/system-administrators/crafter-cli/index.rst
source/system-administrators/crafter-cli/list-remotes.rst
source/system-administrators/crafter-cli/sync-from.rst
source/system-administrators/crafter-cli/sync-to.rst
source/system-administrators/index.rst

[3.1] Add crafter-cli documentation

---

source/system-administrators/crafter-cli/add-environment.rst
source/system-administrators/crafter-cli/add-remote.rst
source/system-administrators/crafter-cli/crafter-cli-commands.rst
source/system-administrators/crafter-cli/create-site.rst
source/system-administrators/crafter-cli/index.rst
source/system-administrators/crafter-cli/list-remotes.rst
source/system-administrators/crafter-cli/sync-from.rst
source/system-administrators/crafter-cli/sync-to.rst
source/system-administrators/index.rst

[master] Add crafter-cli documentation

---

source/acknowledgements/index.rst

Update OSS acknowledgements for 3.1.11

Update OSS acknowledgements for 3.1.11

---

source/developers/projects/engine/api/script-sandbox-configuration.rst

Add note about Groovy sandbox limitation #4411

[3.1] Add note about Groovy sandbox limitation #4411

---

source/developers/projects/engine/api/script-sandbox-configuration.rst

Add note for Groovy sandbox limitation #4411

[master] Add note for Groovy sandbox limitation #4411

---

source/system-administrators/activities/security/setup-cloudfront-signed-cookies-in-crafter.rst
source/system-administrators/index.rst

Add instructions on how to setup CloudFront signed cookies in Crafter CMS #4403

[3.1] Add instructions on how to setup CloudFront signed cookies in Crafter CMS #4403

---

source/system-administrators/activities/security/setup-cloudfront-signed-cookies-in-crafter.rst
source/system-administrators/index.rst

Add instructions on how to setup CloudFront signed cookies in Crafter CMS #4403

[master] Add instructions on how to setup CloudFront signed cookies in Crafter CMS #4403

---

source/system-administrators/upgrade/index.rst
source/system-administrators/upgrade/upgrade-notes-for-re-encrypting-values.rst

Add note for re-encryption process included in 3.1.9 in preparation for the 3.2.0 notes

[master] Add note for re-encryption process performed in 3.1.9 and ter 3.1.x version #4408

---

source/developers/content-modeling.rst

Add description for content type property - controller

[3.1] Add description for content type property - controller

---

source/developers/content-modeling.rst

Add description for content type property controller

[master] Add description for content type property controller

---

source/_static/code/system-admin/CloudFrontUtils.groovy
source/system-administrators/activities/security/setup-cloudfront-signed-cookies-in-crafter.rst

Update CloudFront signed cookies instructions - add missing groovy file

[master] Update CloudFront signed cookies instructions

---

source/_static/code/system-admin/CloudFrontUtils.groovy
source/system-administrators/activities/security/setup-cloudfront-signed-cookies-in-crafter.rst

Update CloudFront signed cookies instructions - add missing groovy file

[3.1] Update CloudFront signed cookies instructions

---

source/developers/projects/studio/api/activity/get-user-activity.rst
source/developers/projects/studio/api/security/get-user-permissions.rst
source/developers/projects/studio/api/security/get-user-roles.rst
source/developers/projects/studio/api/site/get-sites-per-user.rst
source/developers/projects/studio/api/workflow/go-delete.rst
source/developers/projects/studio/api/workflow/reject.rst

[3.1] Update parameters

---

source/developers/projects/studio/api/activity/get-user-activity.rst
source/developers/projects/studio/api/security/get-user-permissions.rst
source/developers/projects/studio/api/security/get-user-roles.rst
source/developers/projects/studio/api/site/get-sites-per-user.rst
source/developers/projects/studio/api/workflow/go-delete.rst
source/developers/projects/studio/api/workflow/reject.rst

[master] Update parameters

---

source/system-administrators/activities/studio-clustering-two-nodes-with-arbiter.rst

[3.1] Fix typo in logs path

---

source/system-administrators/activities/studio-clustering-two-nodes-with-arbiter.rst

[master] Fix typo in logs path

---

source/system-administrators/activities/security/setup-cloudfront-signed-cookies-in-crafter.rst

Update instruction text for setting up CloudFront signed cookies in Crafter based on feedback

[3.1] Update based on feedback #4403

---

source/system-administrators/activities/security/setup-cloudfront-signed-cookies-in-crafter.rst

Update instruction text for setting up CloudFront signed cookies in Crafter based on feedback

[master] Update based on feedback #4403

---

source/acknowledgements/index.rst
source/developers/developer-workflow/index.rst

- Update OSS acknowledgement for 3.1.12
- Fix undefined label warning

Update OSS acknowledgement for 3.1.12

---

source/site-administrators/studio/webdav-profiles-configuration.rst

Update WebDAV config options #4374

[3.1] Update WebDAV config options #4374

---

source/site-administrators/studio/webdav-profiles-configuration.rst

Update WebDAV configuration options #4374

[master] Update WebDAV configuration options #4374

---

source/developers/content-inheritance.rst

Fix typo "unde" in XML code caption

---

source/developers/content-type-component.rst

Minor grammar fix for multiple controls

---

source/conf.py

Update Studio API version 

---

source/developers/cook-books/how-tos/configure-crafter-on-docker-for-local-dev-tools.rst
source/developers/cook-books/how-tos/index.rst
source/developers/projects/engine/api/groovy-api.rst
source/getting-started/quick-start-guide.rst

Updates based on feedback provided by Russ

[master] Updates based on feedback provided by Russ

---

source/developers/cook-books/how-tos/configure-crafter-on-docker-for-local-dev-tools.rst
source/developers/cook-books/how-tos/index.rst
source/developers/projects/engine/api/groovy-api.rst
source/getting-started/quick-start-guide.rst

Updates based on feedback provided by Russ

[3.1] Updates based on feedback provided by Russ

---

source/developers/projects/engine/api/groovy-api.rst

https://github.com/craftercms/docs/pull/1128/commits/84d94f072e713a3ab7c44b68d3ec6caa4f231985

Same change as PR 1128. Should be templateModel.

---

source/site-administrators/engine/engine-site-configuration.rst

Update Engine site configuration doc

[master] Update Engine site configuration doc

---

source/site-administrators/engine/engine-site-configuration.rst

Update Engine site configuration doc

[3.1] Update Engine site configuration doc

---

source/getting-started/quick-start-guide.rst

Fix typo in quick start guide

---

source/site-administrators/studio/blob-stores.rst

Add link to example using blob stores config

[master] Add link to example using blob stores config

---

source/site-administrators/studio/blob-stores.rst

Add link to example using blob stores config

[3.1] Add link to example using blob stores config

---

source/developers/projects/studio/api/publish/status.rst

Update publish status api messages

[3.1] Update publish status api messages

---

source/developers/projects/studio/api/publish/status.rst

Update publish status api messages

[master] Update publish status api messages

---

source/developers/content-inheritance.rst

Highlight the same line in the article descriptor

---

source/developers/content-inheritance.rst
source/developers/cook-books/how-tos/working-with-crafter-studios-api.rst

- Fix warnings in working with Studio api's
- Highlight the same line in the article descriptor

[master] Fix warnings and highlight

---

source/system-administrators/activities/reindexing-content-in-prod.rst

[3.1] Update reindexing

---

source/system-administrators/activities/reindexing-content-in-prod.rst
source/system-administrators/activities/reindexing-content.rst

[master] Update reindexing

---

source/system-administrators/upgrade/docker/config/config-changes-3.1.10-to-3.1.11.rst
source/system-administrators/upgrade/docker/config/config-changes-3.1.11-to-3.1.12.rst
source/system-administrators/upgrade/docker/config/config-changes-3.1.12-to-3.1.13.rst
source/system-administrators/upgrade/docker/config/index.rst

Fixed Sphinx issues

---

source/developers/plugins/site-plugins.rst

Fix spacing of nested list and highlight top list

Fix spacing of nested list and highlight top list

---

source/developers/developer-workflow/connecting-prod-cms-to-dev-workflow.rst
source/developers/developer-workflow/developer-workflow.rst
source/developers/developer-workflow/implementation-devops-workflow.rst
source/developers/developer-workflow/implementation-prod-repo-sync.rst

Propagate updates from master to 3.1 for developer workflow

Propagate updates from master to 3.1 for developer workflow

---

source/developers/developer-workflow/implementation-devops-workflow.rst
source/developers/developer-workflow/implementation-prod-repo-sync.rst

Fix overline warnings in developer workflow

Fix overline warnings in developer workflow

---

source/system-administrators/activities/security/security-change-defaults.rst

Add how to set cookies to http only and secure

{3.1] Add how to set cookies to http only and secure

---

source/system-administrators/activities/security/security-change-defaults.rst

Add how to set cookies to http only and secure

[master] Add how to set cookies to http only and secure

---

source/developers/cook-books/how-tos/integrating-crafter-cms-with-bitbucket.rst
source/developers/cook-books/how-tos/integrating-crafter-cms-with-github.rst
source/developers/cook-books/how-tos/integrating-crafter-cms-with-gitlab.rst
source/site-administrators/remote-repositories.rst

Add note when using ssh keys to use RSA

[3.1] Add note when using ssh keys to use RSA

---

source/developers/cook-books/how-tos/integrating-crafter-cms-with-bitbucket.rst
source/developers/cook-books/how-tos/integrating-crafter-cms-with-github.rst
source/developers/cook-books/how-tos/integrating-crafter-cms-with-gitlab.rst
source/site-administrators/remote-repositories.rst

Add note when using ssh keys to use RSA

[master] Add note when using ssh keys to use RSA

---

source/site-administrators/remote-repositories.rst

Link to a page that is more useful.

---

source/system-administrators/activities/reindexing-content.rst

Studio reindex involves 2 separate indexes

---

source/system-administrators/activities/debugging-ssh-issues.rst

Use openssl command to generate RSA private key

---

source/includes/setup-ssh-keys.rst
source/site-administrators/remote-repositories.rst
source/system-administrators/activities/debugging-ssh-issues.rst
source/system-administrators/activities/delivery/setup-delivery-using-aws-ami.rst
source/system-administrators/activities/kubernetes/simple-authoring-single-instance-kubernetes-deployment.rst
source/system-administrators/activities/kubernetes/simple-kubernetes-deployment.rst
source/system-administrators/activities/kubernetes/studio-clustering-with-kubernetes-deployment.rst
source/system-administrators/activities/reindexing-content.rst

Update ssh-keygen command and fix some formatting

Update ssh-keygen and fix some formatting

---

source/includes/setup-ssh-keys.rst
source/site-administrators/remote-repositories.rst
source/system-administrators/activities/debugging-ssh-issues.rst
source/system-administrators/activities/delivery/setup-delivery-using-aws-ami.rst
source/system-administrators/activities/kubernetes/simple-authoring-single-instance-kubernetes-deployment.rst
source/system-administrators/activities/kubernetes/simple-kubernetes-deployment.rst
source/system-administrators/activities/kubernetes/studio-clustering-with-kubernetes-deployment.rst
source/system-administrators/activities/reindexing-content.rst

Updates from 3.1 for ssh-keygen and reindexing

[master] Updates from 3.1 for ssh-keygen and reindexing

---

source/system-administrators/activities/debugging-ssh-issues.rst

Fix rendering of note in debugging ssh issues

Fix rendering of note in debugging ssh issues

---

source/developers/cook-books/aws/use-s3-to-store-assets.rst
source/site-administrators/studio/publishing-assets-in-external-storage.rst

Add note for preferred way for S3 storage

[3.1] Add note for preferred way for S3 storage 

---

source/developers/cook-books/aws/use-s3-to-store-assets.rst
source/site-administrators/studio/publishing-assets-in-external-storage.rst

Add note for preferred way for S3 storage

[master] Add note for preferred way for S3 storage

---

source/system-administrators/activities/clustering/changing-git-url-format-in-cluster.rst

Add recreate remote updates based on review

[master] Add recreate remote updates based on review

---

source/developers/projects/engine/api/templating-api.rst

https://github.com/craftercms/craftercms/issues/4600

Add docs for renderComponent macro

---

source/developers/projects/studio/api/site/create-site.rst

https://github.com/craftercms/craftercms/issues/3514

Remove create & push option from create site API

---

source/developers/plugins/site-plugins.rst
source/system-administrators/devcontentops-toolkit/add-environment.rst
source/system-administrators/devcontentops-toolkit/add-remote.rst
source/system-administrators/devcontentops-toolkit/copy-plugin.rst
source/system-administrators/devcontentops-toolkit/crafter-cli-commands.rst
source/system-administrators/devcontentops-toolkit/index.rst
source/system-administrators/devcontentops-toolkit/list-sites.rst

Update crafter-cli commands - add copy-plugin

Update crafter-cli commands

---

source/site-administrators/engine/engine-headers-based-authentication.rst

https://github.com/craftercms/craftercms/issues/4603

Update doc for engine headers authentication

---

source/site-administrators/engine/engine-headers-based-authentication.rst

https://github.com/craftercms/craftercms/issues/4603

3.1.x/feature/4603

---

source/site-administrators/engine/engine-headers-based-authentication.rst

Fix spacing warnings in engine header article

[3.1] Fix spacing warnings in engine header article

---

source/developers/redirect.rst

Fix typo for field name for redirecting using content type

[3.1] Fix typo for field name for redirecting using content type

---

source/developers/redirect.rst

Fix typo for field name for redirecting using content type

[master] Fix typo for field name for redirecting using content type

---

source/developers/projects/engine/api/groovy-api.rst

Fix typo in sitemap.groovy example

[master] Fix typo in sitemap.groovy example

---

source/release-notes/3-1-10.rst
source/release-notes/3-1-11.rst
source/release-notes/3-1-12.rst
source/release-notes/3-1-13.rst
source/release-notes/3-1-9.rst
source/system-administrators/upgrade/index.rst
source/system-administrators/upgrade/upgrade-notes-for-re-encrypting-values.rst

Update upgrade notes on re-encryption

Update upgrade notes on re-encryption

---

source/site-administrators/studio/rte2-setup.rst

Update docs to clarify RTE toolbar config details

[master] Update docs to clarify RTE toolbar config details

---

source/site-administrators/studio/rte2-setup.rst

Fix warnings in RTE tool bar config clarification

[3.1] Fix warnings in RTE tool bar config clarification

---

source/site-administrators/studio/rte2-setup.rst

Fix warnings in RTE tool bar config clarification

[master] Fix warnings in RTE tool bar config clarification

---

source/developers/developer-workflow/implementation-devops-workflow.rst
source/includes/git-changes-note.rst
source/site-administrators/publishing-and-status.rst
source/site-administrators/remote-repositories.rst

Update bulk and publish by commit id description

[3.1] Update bulk and publish by commit id description

---

source/developers/developer-workflow/implementation-devops-workflow.rst
source/includes/git-changes-note.rst
source/site-administrators/publishing-and-status.rst
source/site-administrators/remote-repositories.rst

Update bulk and publish by commit id description

[master] Update bulk and publish by commit id description

---

source/site-administrators/studio/rte2-setup.rst

Updates - use macro {site} in getPluginFile api #4618

[3.1] Updates - use macro {site} in getPluginFile api #4618

---

source/site-administrators/studio/rte2-setup.rst

Updates - use macro {site} in getPluginFile api #4618

[master] Updates - use macro {site} in getPluginFile api #4618

---

source/acknowledgements/index.rst

Update OSS acknowledgements

---

source/system-administrators/devcontentops-toolkit/add-environment.rst
source/system-administrators/devcontentops-toolkit/add-remote.rst
source/system-administrators/devcontentops-toolkit/create-site.rst
source/system-administrators/devcontentops-toolkit/list-remotes.rst
source/system-administrators/devcontentops-toolkit/sync-from.rst
source/system-administrators/devcontentops-toolkit/sync-to.rst

Update cli profile parameter description

[3.1] Update cli profile parameter description

---

source/system-administrators/devcontentops-toolkit/add-environment.rst
source/system-administrators/devcontentops-toolkit/add-remote.rst
source/system-administrators/devcontentops-toolkit/copy-plugin.rst
source/system-administrators/devcontentops-toolkit/create-site.rst
source/system-administrators/devcontentops-toolkit/list-remotes.rst
source/system-administrators/devcontentops-toolkit/list-sites.rst
source/system-administrators/devcontentops-toolkit/sync-from.rst
source/system-administrators/devcontentops-toolkit/sync-to.rst

Update cli profile parameter description

[master] Update cli profile parameter description

---

source/site-administrators/engine/engine-crafter-profile-configuration.rst
source/system-administrators/profile/admin/guides/tenants.rst

[3.1] Update header prefix used

---

source/site-administrators/engine/engine-crafter-profile-configuration.rst
source/system-administrators/profile/admin/guides/tenants.rst

[master] Update header prefix used

---

source/developers/projects/engine/api/groovy-api.rst
source/developers/projects/engine/api/unit-testing-groovy-code.rst

Add classes of the variables that can be mocked for unit testing Groovy code

[3.1] Updates for Groovy unit testing based on review

---

source/developers/projects/engine/api/groovy-api.rst
source/developers/projects/engine/api/unit-testing-groovy-code.rst

Add classes of the variables that can be mocked for unit testing Groovy code

[master] Updates for Groovy unit testing based on review

---

source/system-administrators/activities/debugging-ssl-issues.rst
source/system-administrators/activities/troubleshooting.rst

Add note for disabled TLS v1 and v1.1 #4687

[master] Add note for disabled TLS v1 and v1.1 #4687

---

source/system-administrators/profile/admin/index.rst

Update war filename of crafter profile admin

[3.1] Update war filename of crafter profile admin

---

source/system-administrators/profile/admin/index.rst

Update war filename of crafter profile admin

[master] Update war filename of crafter profile admin

---

source/site-administrators/engine/engine-headers-based-authentication.rst

Fix warning in engine headers based auth

[master] Fix warning in engine headers based auth

---

source/site-administrators/engine/engine-headers-based-authentication.rst

Fix warning in engine headers based auth

[3.1] Fix warning in engine headers based auth

---

source/developers/projects/studio/api/api-version1.rst
source/developers/projects/studio/api/site/get-configuration.rst
source/developers/projects/studio/api/site/write-configuration.rst

Update deprecated site management apis #4738

[3.1] Update deprecated site management apis #4738

---

source/conf.py
source/developers/projects/studio/api/api-version1.rst
source/developers/projects/studio/api/site/get-configuration.rst
source/developers/projects/studio/api/site/write-configuration.rst

Update deprecated site management apis #4738

[master] Update deprecated site management apis #4738

---

source/developers/projects/engine/api/script-sandbox-configuration.rst

craftersoftware/craftercms#240

Update docs for groovy sandbox

---

source/developers/cook-books/how-tos/override-logging-levels.rst

Update how to override logging levels #4740

[3.1] Update how to override logging levels #4740

---

source/developers/projects/craftercms/index.rst
source/developers/projects/search/api/index-management/create-index.rst
source/developers/projects/search/api/index-management/delete-index.rst
source/developers/projects/search/api/index-management/index-info.rst
source/developers/projects/search/api/index.rst
source/developers/projects/search/api/search/v2/commit.rst
source/developers/projects/search/api/search/v2/delete.rst
source/developers/projects/search/api/search/v2/search.rst
source/developers/projects/search/api/search/v2/update-content.rst
source/developers/projects/search/api/search/v2/update.rst
source/system-administrators/activities/security/security-change-defaults.rst

https://github.com/craftersoftware/craftercms/issues/246

Document new access token for Crafter Search

---

source/system-administrators/deployer/processors-guide.rst

Clarify how filteredChangeSet is created

---

source/system-administrators/deployer/processors-guide.rst

Clarify how filteredChangeSet is created - pushed up from 3.1

Clarify how filteredChangeSet is created - pushed up from 3.1

---

source/developers/cook-books/how-tos/migrate-site-to-elasticsearch.rst

https://github.com/craftercms/craftercms/issues/4751

Update ES migration guide

---

source/system-administrators/activities/debugging-maven-issues.rst
source/system-administrators/activities/troubleshooting.rst

Add how to fix mvn build error: blocked http repository

Add how to fix mvn build error: blocked http repository

---

source/developers/projects/deployer/api/target-management/unlock-target.rst

[master] Add token to parameters #4705

---

source/developers/projects/deployer/api/target-management/unlock-target.rst

[3.1] Add token to parameters #4705

---

source/developers/projects/engine/engine-configuration-files.rst
source/system-administrators/engine/engine-configuration-overrides.rst
source/system-administrators/index.rst
source/system-administrators/studio/studio-configuration-overrides.rst

* Add Engine properties overrides
* Fix typo in Studio overrides

[3.1] Add Engine properties overrides

---

source/developers/projects/engine/engine-configuration-files.rst
source/system-administrators/engine/engine-configuration-overrides.rst
source/system-administrators/index.rst
source/system-administrators/studio/studio-configuration-overrides.rst

* Add Engine properties overrides
* Push missing Studio override from 3.1

[master] Add Engine properties overrides

---

source/developers/cook-books/content-queries/basic-query-mechanics.rst
source/developers/cook-books/graphql/working-with-graphql.rst
source/developers/projects/search/api/index.rst
source/developers/projects/search/index.rst
source/includes/crafter-search-solr-note.rst
source/includes/how-search-works-solr.rst
source/system-administrators/activities/debugging-search-solr.rst
source/system-administrators/search/index.rst

Add Crafter Search and Solr notes

Add Crafter Search and Solr notes

---

source/acknowledgements/index.rst

Update oss acknowledgement for 3.1.15

Update oss acknowledgement for 3.1.15

---

source/system-administrators/requirements-supported-platforms.rst

[master] Update supported browsers

---

source/developers/content-modeling.rst

Add documentation for parentPath[index] #4804

[3.1] Add documentation for parentPath[index] #4804

---

source/developers/content-modeling.rst

Add documentation for parentPath[index] #4804

[master] Add documentation for parentPath[index] #4804

---

source/developers/projects/studio/api/api-version1.rst
source/developers/projects/studio/api/site/get-configuration.rst
source/developers/projects/studio/api/site/write-configuration.rst

Rollback api changes #4738

---

source/system-administrators/upgrade/docker/config/config-changes-3.1.13-to-3.1.14.rst
source/system-administrators/upgrade/docker/config/config-changes-3.1.14-to-3.1.15.rst
source/system-administrators/upgrade/docker/config/index.rst

Docker upgrade notes for 3.1.14 and 3.1.15

---

source/system-administrators/upgrade/docker/config/config-changes-3.1.15-to-3.1.16.rst
source/system-administrators/upgrade/docker/config/index.rst

Docker upgrade notes for 3.1.15 and 3.1.16

---

source/developers/cook-books/how-tos/working-with-crafter-studios-api.rst

Add note for session id change after authenticating through Spring security

[3.1] Add note for session id change after authenticating through Spring security

---

source/developers/projects/studio/api/site/get-site.rst
source/developers/projects/studio/api/site/get-sites-per-user.rst

Update response objects in get-site and get-sites-per-user api to include `siteUuid` and `name` in the response objects
https://github.com/craftercms/craftercms/issues/4898

Update response objects in get-site and get-sites-per-user api #4898

---

source/acknowledgements/index.rst

Update OSS acknowledgement for 3.1.17

Update OSS acknowledgement for 3.1.17

---

source/developers/projects/studio/api/publish/commits.rst

Refer https://github.com/craftercms/docs/pull/1306

[master] Update sample commits api to use environment live instead of Live

---

source/site-administrators/studio/rte2-setup.rst

Add note to rte for toolbar based on comment from this PR https://github.com/craftercms/docs/pull/1299

[3.1] Add note to rte for toolbar

---

source/site-administrators/studio/using-the-proxy-config.rst

Add note for setting up proxy config running in Docker
https://github.com/craftercms/craftercms/issues/4820

[3.1] Add note for setting up proxy config running in Docker #4820

---

source/site-administrators/studio/using-the-proxy-config.rst

Add note for setting up proxy config running in Docker 
https://github.com/craftercms/craftercms/issues/4820

[master] Add note for setting up proxy config running in Docker #4820

---

source/system-administrators/upgrade/docker/config/config-changes-3.1.16-to-3.1.17.rst
source/system-administrators/upgrade/docker/config/index.rst

Added config changes between 3.1.16 and 3.1.17

---

source/developers/plugins/blueprints.rst

Update screenshot url in descriptor to use default path

Update screenshot url in descriptor to use default path

---

source/developers/cook-books/how-tos/configure-crafter-on-docker-for-local-dev-tools.rst

Add note performance may be slow when using Docker with WSL2
https://github.com/craftercms/craftercms/issues/4895

[3.1] Add note performance may be slow when using Docker with WSL2

---

source/developers/cook-books/how-tos/configure-crafter-on-docker-for-local-dev-tools.rst

Add note performance may be slow when using Docker with WSL2
https://github.com/craftercms/craftercms/issues/4895

[master] Add note performance may be slow when using Docker with WSL2

---

source/developers/plugins/plugin-descriptor.rst

https://github.com/craftercms/craftercms/issues/4962

Update documentation for plugin wiring

---

source/developers/content-modeling.rst

Update groovy class location  https://github.com/craftercms/craftercms/issues/4986

[3.1] Update groovy class location #4986

---

source/developers/content-modeling.rst

Update groovy class location https://github.com/craftercms/craftercms/issues/4986

[master] Update groovy class location #4986

---

source/developers/plugins/plugin-descriptor.rst

Fix warning in plugin descriptor

Fix warning in plugin descriptor

---

source/conf.py
source/developers/projects/studio/api/workflow/get-workflow-affected-paths.rst

- Update get-workflow-affected-paths API https://github.com/craftercms/craftercms/issues/4958
- Update swagger verion

Update get-workflow-affected-paths API #4958

---

source/site-administrators/engine/engine-site-configuration.rst

Push up changes from 3.1 from PR https://github.com/craftercms/docs/pull/1337

Push up changes from 3.1 from PR 1337

---

source/site-administrators/engine/engine-site-configuration.rst

Shorten a long line that was hard to read

---

source/developers/cook-books/how-tos/configure-crafter-on-docker-for-local-dev-tools.rst

Update instructions for configuring Crafter on Docker for local development tools https://github.com/craftercms/craftercms/issues/4896

[master] Update instructions for configuring Crafter on Docker for local development tools #4896

---

source/developers/cook-books/how-tos/configure-crafter-on-docker-for-local-dev-tools.rst

Update instructions for configuring Crafter on Docker for local development tools https://github.com/craftercms/craftercms/issues/4896

[3.1] Update instructions for configuring Crafter on Docker for local development tools #4896

---

source/developers/plugins/plugin-descriptor.rst
source/developers/plugins/studio/plugin-sidebar-example.rst

Adjust plugin wiring example https://github.com/craftercms/craftercms/issues/4962

Adjust plugin wiring example #4962

---

source/getting-started/quick-start-guide.rst
source/getting-started/running-crafter-in-docker.rst
source/system-administrators/activities/installing-and-verifying-prerequisites.rst
source/system-administrators/activities/installing.rst
source/system-administrators/requirements-supported-platforms.rst

Update instructions on installing on Windows

[3.1] Update instructions on installing on Windows

---

source/developers/plugins/index.rst

Fix warning for marketplace/index not included in any toctree

Fix warning for marketplace/index not included in any toctree

---

source/developers/plugins/studio/form-control-plugins.rst

Add additional elements in xml for form control https://github.com/craftercms/craftercms/issues/4808

[3.1] Add additional elements in xml for form control #4808

---

source/developers/plugins/studio/form-control-plugins.rst

Add additional elements in xml for form control https://github.com/craftercms/craftercms/issues/4808

[master] Add additional elements in xml for form control #4808

---

source/system-administrators/engine/engine-configuration-overrides.rst

[master] Add Freemarker flag

---

source/system-administrators/engine/engine-configuration-overrides.rst

[3.1] Add Freemarker flag

---

source/system-administrators/activities/backup-and-recovery.rst

[master] Updates to article

---

source/system-administrators/activities/backup-and-recovery.rst

[3.1] Updates to article

---

source/craftercms_sphinx_theme/layout.html
source/developers/projects/engine/api/site/elasticsearch/search.rst

Add since and last updated tags https://github.com/craftercms/craftercms/issues/3984

Add since and last updated tags #3984

---

source/system-administrators/activities/backup-and-recovery.rst

[master] Update backup instructions

---

source/system-administrators/activities/backup-and-recovery.rst

Fix warning and level heading

---

source/system-administrators/activities/backup-and-recovery.rst

Update backup instruction (pushed from master)

[3.1] Update backup instruction

---

source/system-administrators/activities/reindexing-content-in-prod.rst

Update reindexing without disrupting service https://github.com/craftercms/craftercms/issues/5011

[master] Update reindexing without disrupting service #5011

---

source/developers/projects/engine/api/groovy-api.rst

[3.1] Update groovy api rest script

---

source/site-administrators/encrypting-text-in-config.rst
source/site-administrators/engine/engine-crafter-profile-configuration.rst
source/site-administrators/engine/engine-site-configuration.rst

[3.1] Update example keys

---

source/developers/plugins/plugin-descriptor.rst

https://github.com/craftercms/craftercms/issues/4938

Update plugin wiring docs

---

source/developers/content-inheritance.rst

Fix image/code-block spacing in content inheritance

Fix image/code-block spacing in content inheritance

---

source/conf.py

Fix javadoc version

---

source/acknowledgements/index.rst

Update OSS acknowledgements for 3.1.18

Update OSS acknowledgements for 3.1.18

---

source/developers/cook-books/how-tos/working-with-crafter-studios-api.rst
source/system-administrators/devcontentops-toolkit/add-environment.rst
source/system-administrators/devcontentops-toolkit/add-remote.rst
source/system-administrators/devcontentops-toolkit/copy-plugin.rst
source/system-administrators/devcontentops-toolkit/crafter-cli-commands.rst
source/system-administrators/devcontentops-toolkit/create-site.rst
source/system-administrators/devcontentops-toolkit/index.rst
source/system-administrators/devcontentops-toolkit/list-remotes.rst
source/system-administrators/devcontentops-toolkit/list-sites.rst
source/system-administrators/devcontentops-toolkit/sync-from.rst
source/system-administrators/devcontentops-toolkit/sync-to.rst

Update example for add-environment to use token
Update CrafterCMS names
Add note that connection to CrafterCMS needs to be setup via add-environment in all commands

Update example for crafter-cli "add-environment"

---

source/site-administrators/studio/rte2-setup.rst

Add rte paste plugin callback hooks https://github.com/craftercms/craftercms/issues/5276

Add rte paste plugin callback hooks #5276

---

source/system-administrators/activities/security/security-change-defaults.rst

Update securing your install https://github.com/craftersoftware/craftercms/pull/313

Update securing your install #313

---

source/developers/search-elasticsearch.rst

Update Elasticsearch search examples from editorial  https://github.com/craftercms/craftercms/issues/5317

Update Elasticsearch search examples from editorial #5317

---

source/developers/cook-books/content-queries/basic-query-mechanics.rst
source/developers/cook-books/how-tos/migrate-site-to-elasticsearch.rst
source/developers/search-elasticsearch.rst

https://github.com/craftercms/craftercms/issues/5317

Updates for new Elasticsearch client

---

source/developers/cook-books/active-cache/cache-a-restful-response.rst

Update active cache
- add instructions how to include `cacheTemplate` to the list of allowed beans
- add instructions how to disable all restrictions

[master] Update active cache

---

source/system-administrators/engine/configure-engine-multi-tenancy.rst

Update engine multi-tenancy
- Add note that sending `X-Crafter-Site` header can also be used to change the current site
- Add recommendation to use simple multi-tenancy

Update multi tenancy

---

source/system-administrators/engine/configure-engine-multi-tenancy.rst

Use crafterSite or headers for multi-tenancy https://github.com/craftersoftware/craftercms/issues/319

Use crafterSite or headers for multi-tenancy #319

---

source/site-administrators/studio/rte-configuration.rst

Push rte paste plugin callback hooks from 3.1 to master (https://github.com/craftercms/docs/pull/1413)
https://github.com/craftercms/craftercms/issues/5276

[master] Push rte paste plugin callback hooks from 3.1 #5276

---

source/site-administrators/engine/engine-headers-based-authentication.rst

Update Engine headers authentication https://github.com/craftersoftware/craftercms/issues/318

Update Engine headers authentication

---

source/acknowledgements/index.rst

Update OSS ack for 4.0.0-rc2

---

source/developers/experience-builder.rst

https://github.com/craftercms/craftercms/issues/5316

[5316] Document XB for JavaScript applications

---

source/developers/projects/studio/api/content/write-content.rst
source/site-administrators/engine/engine-mongodb-configuration.rst

Update write content example
Fix warning for could not lex java

[3.1] Update write content example

---

source/developers/projects/studio/api/content/write-content.rst

Update write content example

---

source/developers/cook-books/content-queries/basic-query-mechanics.rst
source/developers/cook-books/how-tos/migrate-site-to-elasticsearch.rst
source/developers/cook-books/how-tos/working-with-crafter-studios-api.rst
source/developers/projects/deployer/api/target-management/deploy-all-targets.rst
source/developers/projects/deployer/api/target-management/deploy-target.rst
source/developers/search-elasticsearch.rst
source/site-administrators/studio/site-policy-configuration.rst
source/system-administrators/devcontentops-toolkit/add-environment.rst
source/system-administrators/devcontentops-toolkit/add-remote.rst
source/system-administrators/devcontentops-toolkit/copy-plugin.rst
source/system-administrators/devcontentops-toolkit/crafter-cli-commands.rst
source/system-administrators/devcontentops-toolkit/create-site.rst
source/system-administrators/devcontentops-toolkit/index.rst
source/system-administrators/devcontentops-toolkit/list-remotes.rst
source/system-administrators/devcontentops-toolkit/list-sites.rst
source/system-administrators/devcontentops-toolkit/sync-from.rst
source/system-administrators/devcontentops-toolkit/sync-to.rst

Add some since/last updated tags https://github.com/craftercms/craftercms/issues/3984

Add since/last updated tags #3984

---

source/developers/experience-builder.rst
source/developers/plugins/project-plugins.rst

Add descriptions for macros in crafter.ftl

Add descriptions for macros in crafter.ftl

---

source/site-administrators/studio/permission-mappings.rst

Fix typos in permission mappings

Fix typos in permission mappings

---

source/developers/content-modeling.rst
source/includes/site-identification-precedence.rst
source/system-administrators/engine/configure-engine-multi-tenancy.rst

Add note for site precedence https://github.com/craftersoftware/craftercms/issues/336

[3.1] Add note for site precedence

---

source/developers/content-modeling.rst
source/includes/project-identification-precedence.rst
source/system-administrators/engine/configure-engine-multi-tenancy.rst

Add note for project precedence https://github.com/craftersoftware/craftercms/issues/336

[master] Add note for project precedence

---

source/site-administrators/studio-configuration.rst

Fix warning for undefined file

Fix warning for undefined file

---

source/conf.py
source/craftercms_sphinx_theme/breadcrumbs.html
source/craftercms_sphinx_theme/layout.html
ui/craftercms-sphinx-theme/src/sphinx/__init__.py
ui/craftercms-sphinx-theme/src/sphinx/breadcrumbs.html
ui/craftercms-sphinx-theme/src/sphinx/layout.html

Open links in new tab https://github.com/craftercms/craftercms/issues/5477

Open links in new tab #5477

---

source/developers/cook-books/graphql/working-with-graphql.rst

Update GraphQL queries https://github.com/craftercms/craftercms/issues/5584

[3.1] Update GraphQL queries #5584

---

source/release-notes/4-0-0.rst

Fix warning "Unexpected indentation" in release notes

Fix warning "Unexpected indentation"

---

source/system-administrators/studio/studio-configuration-overrides.rst

Add crafterSite cookie config and update other sections https://github.com/craftercms/craftercms/issues/5604

Add crafterSite cookie config and update other sections #5604

---

source/system-administrators/activities/clustering.rst
source/system-administrators/activities/clustering/changing-git-url-format-in-cluster.rst
source/system-administrators/activities/clustering/studio-clustering-two-nodes.rst
source/system-administrators/activities/kubernetes/studio-clustering-with-kubernetes-deployment.rst

Add placeholder/note what needs updating in the clustering with kubernetes deployment article https://github.com/craftercms/craftercms/issues/5265

Add placeholder/note what needs updating #5265

---

source/site-administrators/engine/engine-project-security-guide.rst

Update authentication section of Engine project security guide to make it clear that adding the login/logout page is for when using Crafter Profile

[master] Update engine project security guide

---

source/site-administrators/engine/engine-site-security-guide.rst

Update authentication section of Engine project security guide to make it clear that adding the login/logout page is for when using Crafter Profile

[3.1] Update authentication section of Engine security guide

---

source/system-administrators/activities/kubernetes/simple-authoring-single-instance-kubernetes-deployment.rst
source/system-administrators/activities/kubernetes/simple-delivery-kubernetes-deployment.rst
source/system-administrators/activities/kubernetes/simple-kubernetes-deployment.rst

Add notes to kubernetes deployment articles

Add notes to kubernetes deployment articles

---

source/_static/code/kubernetes/simple/authoring-deployment.yaml
source/_static/code/kubernetes/simple/delivery-deployment.yaml
source/_static/code/kubernetes/simple/elasticsearch-deployment.yaml
source/includes/setup-ssh-keys.rst
source/system-administrators/activities/kubernetes/simple-kubernetes-deployment.rst

- Update simple kubernetes deployment example to use 4.0 images
- Update ssh blurb

Update simple kubernetes deployment example

---

source/developers/cook-books/how-tos/working-with-crafter-studios-api.rst

The header name to use with JWT is `Authorization`

Fix JWT header

---

source/.new-ia/by-role/site-admin/project-tools/studio/content-type-editor-config.rst
source/.new-ia/by-role/system-admin/studio/create-site-with-link-to-remote-repo.rst
source/.new-ia/by-role/system-admin/studio/debugging-publishing-issues.rst

Fix some new ia error and some warnings

Fix some new ia error

---

source/new-ia/release-notes/4-0-0.rst
source/release-notes/4-0-0.rst

Add release date in current release notes and update to italics the release notes in the new-ia

Add release date in release notes

---

source/developers/experience-builder.rst
source/site-administrators/studio/user-interface-configuration.rst
source/system-administrators/index.rst
source/system-administrators/upgrade/upgrading-in-context-editing.rst

[5161] How to upgrade from ICE to XB

---

source/developers/experience-builder.rst
source/developers/index.rst
source/developers/upgrading-in-context-editing.rst
source/site-administrators/studio/translation-configuration.rst
source/site-administrators/studio/user-interface-configuration.rst

- Move Upgrading In Context Editing to the developer section
- Fix some warnings

Move Upgrading In Context Editing

---

source/_static/theme/custom.css

https://github.com/craftercms/craftercms/issues/5690

[5690][3.1.x] "version_tag" is not rendering correctly in the docs

---

source/_static/theme/custom.css

https://github.com/craftercms/craftercms/issues/5690

[5690][next] "version_tag" is not rendering correctly in the docs

---

source/conf.py
source/developers/upgrading-in-context-editing.rst
source/release-notes/4-0-1.rst
source/release-notes/index.rst
source/site-administrators/studio/multi-environment-configurations.rst
source/system-administrators/studio/studio-configuration-overrides.rst

- Add release notes for 4.0.1
- add note pointing to `How to upgrade from ICE to XB` https://github.com/craftercms/craftercms/issues/5161

Add release notes for 4.0.1

---

source/acknowledgements/index.rst
source/release-notes/4-0-1.rst

Update OSS acknowledgement for version 4.0.1
Update release date in release notes

Update OSS acknowledgement for version 4.0.1

---

source/developers/projects/engine/api/templating-api.rst
source/new-ia/reference/templating-api.rst

Running Scripts/Controllers in Freemarker templates

Update directive for controller in ftl

---

source/conf.py
source/release-notes/3-1-25.rst
source/release-notes/index.rst

Add release notes for 3.1.25

---

source/release-notes/3-1-25.rst

Update release date for 3.1.25

Update release date

---

source/site-administrators/engine/engine-multi-environment-configuration.rst

Add instructions for multi-environment configuration of SAML2 files
https://github.com/craftercms/craftercms/issues/5747

Add instructions for multi-environment configuration of SAML2 files #5747

---

source/conf.py
source/release-notes/3-1-26.rst
source/release-notes/index.rst

Add release notes for 3.1.26

---

source/developers/cook-books/active-cache/cache-a-restful-response.rst

Fix typo in Active cache restful response example

[master] Fix typo in Active cache restful response example

---

source/developers/cook-books/active-cache/cache-a-restful-response.rst

Fix typo in Active cache restful response example

[3.1] Fix typo in Active cache restful response example

---

source/conf.py

Fix "Edit on GitHub" link to point to 3.1

Fix "Edit on GitHub" link to point to 3.1

---

README.md

[3.1] Update readme

---

README.md

[master] Update readme

---

source/developers/extensions/resources/plugin-host-page-example.rst

Add missing plugin host page example file

Add missing plugin host page example file

---

source/conf.py
source/release-notes/3-1-27.rst
source/release-notes/index.rst

Add release notes for 3.1.27

---

source/developers/extensions/plugin-host.rst
source/developers/extensions/resources/full-screen-plugin-example.rst
source/new-ia/by-role/author/authors-workflows.rst
source/new-ia/by-role/developer/extensions/blueprint-descriptor.rst
source/new-ia/by-role/developer/extensions/blueprints.rst
source/new-ia/by-role/developer/extensions/craftercms-marketplace.rst
source/new-ia/by-role/developer/extensions/index.rst
source/new-ia/by-role/developer/extensions/plugin-descriptor.rst
source/new-ia/by-role/developer/extensions/plugin-host.rst
source/new-ia/by-role/developer/extensions/plugins.rst
source/new-ia/by-role/developer/extensions/resources/form-control-plugins.rst
source/new-ia/by-role/developer/extensions/resources/form-data-source-plugins.rst
source/new-ia/by-role/developer/extensions/resources/full-screen-plugin-example.rst
source/new-ia/by-role/developer/extensions/resources/plugin-dashboard-example.rst
source/new-ia/by-role/developer/extensions/resources/plugin-experience-builder-example.rst
source/new-ia/by-role/developer/extensions/resources/plugin-navmenu-example.rst
source/new-ia/by-role/developer/extensions/resources/plugin-projecttools-example.rst
source/new-ia/by-role/developer/extensions/resources/plugin-sidebar-example.rst
source/new-ia/by-role/developer/extensions/resources/plugin-toolbar-example.rst
source/new-ia/release-notes/4-0-0.rst
source/new-ia/release-notes/4-0-1.rst
source/release-notes/4-0-0.rst

- Push updates to extensions to new-ia
- Update names and corresponding changes needed for links

Push updates to new-ia

---

source/release-notes/3-1-27.rst

Update 3.1.27 release notes

---

source/acknowledgements/index.rst
source/new-ia/contribute/acknowledgements.rst

Update OSS acknowledgements for 4.0.2 release

Update OSS acknowledgements for 4.0.2 release

---

source/new-ia/release-notes/4-0-2.rst
source/release-notes/4-0-2.rst

Update release date for 4.0.2

---

source/includes/ssh-private-key.rst
source/new-ia/by-role/system-admin/authoring/staging.rst
source/new-ia/by-role/system-admin/backup-and-restore.rst
source/new-ia/by-role/system-admin/delivery/setup-delivery-using-aws-ami.rst
source/new-ia/by-role/system-admin/delivery/setup-project-for-delivery.rst
source/new-ia/by-role/system-admin/kubernetes/simple-delivery-kubernetes-deployment.rst
source/new-ia/by-role/system-admin/kubernetes/simple-kubernetes-deployment.rst
source/new-ia/by-role/system-admin/kubernetes/studio-clustering-with-kubernetes-deployment.rst
source/new-ia/by-role/system-admin/production-environment-setup.rst
source/new-ia/release-notes/4-0-2.rst
source/release-notes/4-0-2.rst
source/system-administrators/activities/authoring/staging.rst
source/system-administrators/activities/backup-and-recovery.rst
source/system-administrators/activities/delivery/setup-delivery-using-aws-ami.rst
source/system-administrators/activities/delivery/setup-project-for-delivery.rst
source/system-administrators/activities/kubernetes/simple-delivery-kubernetes-deployment.rst
source/system-administrators/activities/kubernetes/simple-kubernetes-deployment.rst
source/system-administrators/activities/kubernetes/studio-clustering-with-kubernetes-deployment.rst
source/system-administrators/activities/production-environment-setup.rst

- Add note to specify private key when using private key authentication with `init-site.sh`
https://github.com/craftercms/craftercms/issues/5841
- Update some more pages using `site` instead of `project`

Add note to specify private key #5841

---

source/new-ia/by-role/system-admin/clustering/clustering.rst
source/system-administrators/activities/clustering.rst

Add link for S3 replication in `Multi-Region Considerations` section in clustering

Add link for S3 replication

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
source/developers/extensions/resources/plugin-dashboard-example.rst
source/developers/extensions/resources/plugin-navmenu-example.rst
source/developers/projects/engine/api/templating-api.rst
source/getting-started/quick-start-guide.rst
source/new-ia/by-role/developer/extensions/resources/plugin-dashboard-example.rst
source/new-ia/by-role/developer/extensions/resources/plugin-navmenu-example.rst
source/new-ia/by-role/developer/templated/content-type-page.rst
source/new-ia/by-role/developer/templated/security.rst
source/new-ia/by-role/developer/working-with-filters.rst
source/new-ia/by-role/site-admin/project-tools/studio/rte-configuration.rst
source/new-ia/by-role/system-admin/configuration.rst
source/new-ia/by-role/system-admin/delivery/delivery-env-performance-tuning.rst
source/new-ia/by-role/system-admin/delivery/setup-delivery-using-aws-ami.rst
source/new-ia/by-role/system-admin/index.rst
source/new-ia/by-role/system-admin/kubernetes/studio-clustering-with-kubernetes-deployment.rst
source/new-ia/by-role/system-admin/production-environment-setup.rst
source/new-ia/by-role/system-admin/profile/admin/guides/tenants.rst
source/new-ia/by-role/system-admin/profile/index.rst
source/new-ia/by-role/system-admin/upgrade/docker/index.rst
source/site-administrators/studio/rte-configuration.rst
source/system-administrators/activities/kubernetes/studio-clustering-with-kubernetes-deployment.rst
source/system-administrators/profile/admin/guides/tenants.rst

Update text and fix some  warnings

Update text and fix some  warnings

---

source/new-ia/by-role/site-admin/project-tools/engine/engine-saml2-configuration-4-0-2.rst
source/new-ia/by-role/site-admin/project-tools/engine/engine-saml2-configuration.rst
source/new-ia/by-role/system-admin/security/configure-studio-saml-4-0-2.rst
source/new-ia/by-role/system-admin/security/configure-studio-saml.rst
source/site-administrators/engine/engine-saml2-configuration-4-0-2.rst
source/site-administrators/engine/engine-saml2-configuration.rst
source/system-administrators/activities/security/configure-studio-saml-4-0-2.rst
source/system-administrators/activities/security/configure-studio-saml.rst

Update Studio and Engine SAML configuration

Update Studio and Engine SAML configuration

---

source/developers/projects/engine/api/site/graphql/get.rst
source/developers/projects/engine/api/site/graphql/post.rst
source/new-ia/reference/projects/engine/api/site/graphql/get.rst
source/new-ia/reference/projects/engine/api/site/graphql/post.rst

Update examples of Engine GraphQL APIs

Update examples of Engine GraphQL APIs

---

source/conf.py
source/system-administrators/activities/clustering.rst

Updates to clustering for primary publishing node

Updates to clustering for primary publishing node

---

source/conf.py
source/release-notes/3-1-28.rst
source/release-notes/index.rst
source/system-administrators/upgrade/upgrading-to-craftercms-3-1-28-and-later.rst

Add release notes for 3.1.28

---

source/system-administrators/upgrade/upgrading-to-craftercms-3-1-28-and-later.rst

Fix typo in location of tomcat setenv.sh file

Fix typo in location of tomcat setenv.sh file

---

source/new-ia/by-role/system-admin/studio/session-timeout-settings.rst
source/system-administrators/studio/session-timeout-settings.rst

Update session timeout https://github.com/craftercms/craftercms/issues/5892

Update session timeout #5892

---

source/new-ia/by-role/site-admin/project-tools/studio/blob-stores.rst
source/site-administrators/studio/blob-stores.rst

- Update blob stores configuration on use of AWS profiles instead of credentials in the config
- Update blob stores configuration on using AWS service roles https://github.com/craftercms/craftercms/issues/5874

Update blob stores configuration

---

source/conf.py
source/release-notes/3-1-29.rst
source/release-notes/index.rst

Add release notes for 3.1.29

---

source/developers/projects/deployer/api/target-management/recreate-index.rst
source/new-ia/reference/projects/deployer/api/target-management/recreate-index.rst

Update example post to add token https://github.com/craftercms/craftercms/issues/5923

Update example post to add token #5923

---

source/developers/projects/craftercms/index.rst
source/new-ia/by-role/system-admin/maintenance/logging.rst
source/new-ia/reference/projects/craftercms/index.rst
source/system-administrators/activities/logging.rst

Add how to log crafter.sh script output to a file https://github.com/craftercms/craftercms/issues/5887

Add how to log crafter.sh script output to a file #5887

---

source/developers/projects/craftercms/index.rst
source/system-administrators/activities/logging.rst

Add how to log crafter.sh script output to a file https://github.com/craftercms/craftercms/issues/5887

[3.1] Add how to log crafter.sh script output to a file #5887

---

source/developers/projects/craftercms/index.rst
source/new-ia/by-role/system-admin/security/configure-ssl-tls.rst
source/new-ia/reference/projects/craftercms/index.rst
source/system-administrators/activities/security/configure-ssl-tls.rst

Update Tomcat docs links

---

source/developers/projects/studio/api/content/get-content-types.rst
source/new-ia/reference/projects/studio/api/content/get-content-types.rst

Fix typo in Studio get content types API

[master] Fix typo in Studio get content types API

---

source/developers/projects/studio/api/content/get-content-types.rst

Fix typo in Studio get content types API

[3.1] Fix typo in Studio get content types API

---

source/new-ia/by-role/architect/templated.rst
source/new-ia/by-role/author/authors-targeting.rst
source/new-ia/by-role/author/index.rst
source/new-ia/by-role/common/anatomy-of-a-crafter-repository.rst
source/new-ia/by-role/developer/composable/extensions/blueprints.rst
source/new-ia/by-role/developer/index.rst
source/new-ia/by-role/developer/templated/index.rst
source/new-ia/by-role/developer/templated/targeting.rst
source/new-ia/by-role/developer/upgrade/upgrading-in-context-editing.rst
source/new-ia/by-role/index.rst
source/new-ia/by-role/system-admin/installation-and-configuration/configuration/studio/navigating-main-menu.rst
source/new-ia/by-role/system-admin/installation-and-configuration/configuration/studio/studio-configuration-overrides.rst
source/new-ia/by-role/system-admin/installation-and-configuration/index.rst
source/new-ia/by-role/system-admin/maintenance/index.rst
source/new-ia/reference/projects/studio/api/index.rst
source/new-ia/release-notes/4-0-0.rst

Fix some of the warnings in new-ia

Fix some of the warnings in new-ia

---

source/new-ia/by-role/system-admin/security/configure-studio-security.rst

Fix indent error for version tag

Fix indent error for version tag

---

source/new-ia/by-role/system-admin/installation-and-configuration/configuration/studio/studio-configuration-overrides.rst
source/system-administrators/studio/studio-configuration-overrides.rst

Add new variables for overriding username and group name regex https://github.com/craftercms/craftercms/issues/5945

Add new variables for overriding username and group name regex #5945

---

source/conf.py
source/developers/extensions/plugins.rst
source/developers/extensions/resources/form-control-plugins.rst
source/developers/extensions/resources/form-data-source-plugins.rst
source/developers/projects/studio/api/api-version1.rst
source/developers/projects/studio/api/aws/mediaconvert/post-upload.rst
source/developers/projects/studio/api/aws/s3/post-upload.rst
source/developers/projects/studio/api/index.rst
source/developers/projects/studio/api/site/get-configuration.rst
source/developers/projects/studio/api/site/write-configuration.rst
source/developers/projects/studio/api/workflow/get-workflow-affected-paths.rst
source/developers/projects/studio/api/workflow/go-delete.rst
source/new-ia/by-role/common/plugin-management.rst
source/new-ia/by-role/developer/composable/extensions/plugins.rst
source/new-ia/by-role/developer/composable/extensions/resources/form-control-plugins.rst
source/new-ia/by-role/developer/composable/extensions/resources/form-data-source-plugins.rst
source/new-ia/by-role/site-admin/project-tools/studio/rte-configuration.rst
source/new-ia/reference/projects/studio/api/api-version1.rst
source/new-ia/reference/projects/studio/api/aws/mediaconvert/post-upload.rst
source/new-ia/reference/projects/studio/api/aws/s3/post-upload.rst
source/new-ia/reference/projects/studio/api/index.rst
source/new-ia/reference/projects/studio/api/site/get-configuration.rst
source/new-ia/reference/projects/studio/api/site/write-configuration.rst
source/new-ia/reference/projects/studio/api/workflow/get-workflow-affected-paths.rst
source/site-administrators/plugin-management.rst
source/site-administrators/studio/rte-configuration.rst

Update links to display some text instead of the verbose link

Update links to display some text instead of the verbose link

---

source/developers/extensions/plugins.rst
source/developers/extensions/resources/form-control-plugins.rst
source/developers/extensions/resources/form-data-source-plugins.rst
source/developers/projects/studio/api/api-version1.rst
source/developers/projects/studio/api/aws/mediaconvert/post-upload.rst
source/developers/projects/studio/api/aws/s3/post-upload.rst
source/developers/projects/studio/api/site/get-configuration.rst
source/developers/projects/studio/api/site/write-configuration.rst
source/developers/projects/studio/api/workflow/get-workflow-affected-paths.rst
source/developers/projects/studio/api/workflow/go-delete.rst
source/new-ia/by-role/common/plugin-management.rst
source/new-ia/by-role/developer/composable/extensions/plugins.rst
source/new-ia/by-role/developer/composable/extensions/resources/form-control-plugins.rst
source/new-ia/by-role/developer/composable/extensions/resources/form-data-source-plugins.rst
source/new-ia/by-role/site-admin/project-tools/studio/rte-configuration.rst
source/new-ia/reference/projects/studio/api/api-version1.rst
source/new-ia/reference/projects/studio/api/aws/mediaconvert/post-upload.rst
source/new-ia/reference/projects/studio/api/aws/s3/post-upload.rst
source/new-ia/reference/projects/studio/api/index.rst
source/new-ia/reference/projects/studio/api/site/get-configuration.rst
source/new-ia/reference/projects/studio/api/site/write-configuration.rst
source/new-ia/reference/projects/studio/api/workflow/get-workflow-affected-paths.rst
source/site-administrators/plugin-management.rst
source/site-administrators/studio/rte-configuration.rst

Fix broken links (Remove extra `/` after `en/4.0`)

Fix broken links

---

source/system-administrators/studio/studio-configuration-overrides.rst

Update validation regex samples [#5983](https://github.com/craftercms/craftercms/issues/5983)

Update validation regex samples #5983

---

source/developers/extensions/plugins.rst
source/developers/projects/studio/api/index.rst

Put Studio API docs in iframe

---

source/new-ia/by-role/system-admin/installation-and-configuration/index.rst
source/new-ia/by-role/system-admin/performance-and-scaling/authoring-env-performance-tuning.rst
source/new-ia/by-role/system-admin/performance-and-scaling/delivery-env-performance-tuning.rst
source/new-ia/by-role/system-admin/performance-and-scaling/index.rst
source/new-ia/by-role/system-admin/security/configure-engine-security.rst
source/new-ia/by-role/system-admin/security/configure-studio-security.rst
source/new-ia/by-role/system-admin/security/index.rst
source/new-ia/by-role/system-admin/upgrade/index.rst
source/new-ia/contribute/index.rst
source/new-ia/getting-started/docker.rst
source/new-ia/reference/javascript-sdk.rst

Fix some warnings

---

source/acknowledgements/index.rst
source/new-ia/contribute/acknowledgements.rst

Update OSS acknowledgements for 4.0.3

Update OSS acknowledgements for 4.0.3

---

source/includes/freemarker-variables.rst
source/includes/global-groovy-variables.rst
source/new-ia/includes/freemarker-variables.rst
source/new-ia/includes/global-groovy-variables.rst

Update links in Groovy and Freemarker variables tables

Update links in Groovy and Freemarker variables tables

---

source/developers/projects/deployer/api/target-management/get-all-targets.rst
source/new-ia/reference/modules/search/index.rst
source/new-ia/reference/rest-content-retrieval-api.rst

Fix broken URLs and update Deployer example for get-all-targets

Fix broken URLs and update Deployer example

---

source/developers/cook-books/aws/upload-transcode-video.rst
source/new-ia/by-role/developer/common/aws/upload-transcode-video.rst

Add links to AWS MediaConvert permissions in upload and transcode video doc

Update upload and transcode video docs

---

source/new-ia/by-role/system-admin/installation-and-configuration/configuration/studio/studio-configuration-overrides.rst
source/system-administrators/studio/studio-configuration-overrides.rst

Fix unterminated/bad yaml escaping in validation regex in the Studio config overrides article

Fix unterminated/bad yaml escaping in validation regex

---

source/new-ia/by-role/system-admin/security/configure-studio-security.rst
source/system-administrators/activities/security/configure-studio-saml.rst

Add note in Studio SAML article

Add note in Studio SAML article

---

source/developers/experience-builder.rst
source/new-ia/by-role/developer/common/adding-experience-builder.rst

Updates to experience builder in new-ia pulled from https://github.com/craftercms/docs/pull/1636

Updates to experience builder in new-ia

---

source/conf.py

Update "edit_on_github" link to point to 4.0

[4.0] Update "edit_on_github" link to point to 4.0

---

source/conf.py
source/release-notes/4-0-4.rst
source/release-notes/index.rst

Add release notes for 4.0.4

---

source/developers/plugins/studio/form-control-plugins.rst

Fix broken link

---

source/conf.py
source/release-notes/4-0-5.rst
source/release-notes/index.rst

Add release notes for 4.0.5

---

source/contribute/acknowledgements.rst

Update OSS acknowledgements for 4.1.0

Update OSS acknowledgements for 4.1.0

---

source/by-role/developer/index.rst

Update search resource  https://github.com/craftercms/craftercms/issues/6134

Update search resource #6134

---

source/by-role/architect/index.rst
source/by-role/author/index.rst
source/by-role/developer/common/content-modeling/content-modeling.rst
source/by-role/developer/common/security.rst
source/by-role/developer/common/static-content-access.rst
source/by-role/site-admin/index.rst
source/by-role/system-admin/installation-and-configuration/index.rst
source/by-role/system-admin/security/index.rst
source/getting-started/index.rst
source/includes/content-retrieval-apis.rst
source/index.rst
source/reference/groovy-development.rst
source/reference/java-api.rst
source/reference/javascript-sdk.rst
source/reference/multi-environment-support.rst
source/reference/project-tools/engine/engine-saml2-configuration.rst
source/release-notes/4-1-0-breaking-changes.rst
source/release-notes/4-1-0.rst

Updates from feedback, fix broken links, warnings, etc

Updates from feedback, fix broken links, warnings, etc

---

source/reference/index.rst

Update links for REST APIs to use existing ones in Reference section

Update links for REST APIs to use existing ones

---

source/by-role/developer/common/search.rst

Update search client name

---

source/conf.py
source/release-notes/4-0-6.rst
source/release-notes/index.rst

Add release notes for 4.0.6

---

source/by-role/developer/composable/extensions/resources/plugin-sidebar-example.rst
source/reference/project-tools/studio/user-interface-configuration.rst

Update icon id https://github.com/craftercms/craftercms/issues/6144

[master] Update icon id #6144

---

source/developers/extensions/resources/plugin-sidebar-example.rst
source/new-ia/by-role/developer/composable/extensions/resources/plugin-sidebar-example.rst
source/new-ia/reference/project-tools/studio/user-interface-configuration.rst
source/site-administrators/studio/user-interface-configuration.rst

Update icon id https://github.com/craftercms/craftercms/issues/6144

[4.0] Update icon id #6144

---

source/by-role/system-admin/installation-and-configuration/configuration/studio/global-permission-mappings-config.rst
source/includes/available-permissions.rst
source/reference/project-tools/studio/permission-mappings.rst

Update permissions listUpdate permissions list https://github.com/craftercms/craftercms/issues/6117

Update permissions list #6117

---

source/reference/project-tools/studio/user-interface-configuration.rst

- Updates based on review https://github.com/craftercms/craftercms/issues/6144
- Update headings/overlines

Updates based on review #6144

---

source/reference/modules/studio/index.rst

Update the configurations table for Studio

Update the configurations table for Studio

---

source/conf.py
source/release-notes/4-0-7.rst
source/release-notes/index.rst

Add release notes for 4.0.7

---

source/by-role/system-admin/installation-and-configuration/production-environment-setup.rst

Update production environment setup for OpenSearch

Update production environment setup for OpenSearch

---

source/contribute/acknowledgements.rst

Fix line breaks

---

source/by-role/author/index.rst
source/by-role/developer/common/static-content-access.rst
source/by-role/site-admin/index.rst
source/by-role/system-admin/installation-and-configuration/configuration/studio/users-groups-management.rst
source/by-role/system-admin/installation-and-configuration/configuration/studio/users-groups/putting-it-all-together.rst
source/by-role/system-admin/installation-and-configuration/configuration/studio/users-groups/roles-and-permissions.rst
source/by-role/system-admin/security/configure-engine-security.rst
source/by-role/system-admin/security/configure-studio-security.rst
source/includes/available-permissions.rst
source/reference/modules/studio/index.rst
source/reference/project-tools/studio/role-mappings.rst

Update project admin index page
Alphabetize permissions list

Update project admin index page

---

source/by-role/system-admin/security/index.rst
source/getting-started/index.rst

Installation updates warning fix

Installation updates warning fix

---

source/reference/modules/deployer/index.rst

Add deployer custom processors

Add deployer custom processors

---

source/developers/devcontentops.rst

Fix broken link in devcontentops

Fix broken link in devcontentops

---

source/by-role/developer/common/static-content-access.rst
source/by-role/site-admin/index.rst
source/by-role/system-admin/configuration/delivery/setup-serverless-delivery.rst
source/by-role/system-admin/configuration/index.rst
source/by-role/system-admin/performance-and-scaling/clustering/studio-clustering-two-nodes.rst
source/by-role/system-admin/security/configure-studio-saml-4-0-2-and-earlier.rst
source/by-role/system-admin/security/index.rst
source/by-role/system-admin/security/setting-up-a-simple-ldap-server.rst
source/reference/modules/studio/administration.rst
source/reference/modules/studio/configuration.rst
source/reference/project-tools/index.rst
source/reference/project-tools/studio/notification-configuration.rst

Fix warnings

---

source/_static/code/developer/groovy-unit-test/build.gradle
source/reference/groovy-development.rst

Update Groovy Unit test

---

source/reference/modules/studio/configuration.rst
source/reference/modules/studio/security.rst

Fix errors

---

source/conf.py
source/release-notes/3-1-31.rst
source/release-notes/index.rst

Add release notes for 3.1.31

---

source/reference/modules/engine/configuration.rst
source/reference/modules/studio/configuration.rst

Update http headers properties

Update http headers properties

---

source/reference/modules/engine/configuration.rst

Updates to engine config

---

source/by-role/developer/common/adding-a-new-language.rst

Update based on review for adding a new language https://github.com/craftercms/craftercms/issues/6171

Update based on review for adding a new language

---

source/by-role/author/index.rst
source/by-role/developer/common/targeting.rst
source/by-role/site-admin/index.rst
source/getting-started/your-first-project/templated.rst
source/reference/project-tools/studio/user-interface-configuration.rst

Fix some titles and anchors https://github.com/craftercms/craftercms/issues/6109

Fix some titles and anchors #6109

---

source/by-role/author/index.rst
source/by-role/developer/common/content-access.rst
source/by-role/developer/common/working-with-dates-groovy.rst
source/by-role/developer/index.rst
source/reference/modules/engine/configuration.rst
source/reference/redirects.rst

Updates to Engine configuration & add table in developer

Updates to Engine configuration & add table in developer

---

source/by-role/author/index.rst
source/reference/modules/engine/configuration.rst

Updates engine config properties

Updates engine config properties

---

source/by-role/system-admin/performance-and-scaling/index.rst
source/reference/modules/engine/index.rst
source/reference/modules/engine/security.rst

Updates for some more security properties and add toctree for performance and scaling

Updates for some more security properties and add toctree for performance and scaling

---

source/reference/modules/engine/configuration.rst

Update for Engine status API health check https://github.com/craftersoftware/craftercms/issues/558

Update for Engine status API health check

---

source/_static/theme/custom.css
source/by-role/developer/common/content-modeling/content-modeling.rst
source/by-role/system-admin/maintenance/index.rst
source/by-role/system-admin/performance-and-scaling/authoring-env-performance-tuning.rst
source/by-role/system-admin/performance-and-scaling/delivery-env-performance-tuning.rst
source/conf.py
source/includes/application-performance-tuning.rst
source/includes/deployer-performance-tuning.rst
source/includes/form-controls/list-form-controls.rst
source/includes/formatting.rst
source/includes/s5defs.rst
source/support.rst

Add colors and updates to performance tuning

Add colors and updates to performance tuning

---

source/by-role/system-admin/performance-and-scaling/clustering.rst
source/reference/modules/studio/security.rst

[master] Fix broken links

---

source/by-role/system-admin/performance-and-scaling/clustering.rst

Fix broken link in clustering

---

source/reference/groovy-development.rst

Update rest scripts in groovy development https://github.com/craftersoftware/craftercms/issues/344

Update groovy rest controller

---

source/reference/modules/studio/administration.rst
source/reference/modules/studio/configuration/index.rst
source/reference/modules/studio/configuration/user-interface-configuration.rst
source/reference/modules/studio/index.rst

Fix warnings and add toctree for sidebar nav

Fix warnings and add toctree for sidebar nav

---

source/by-role/developer/common/working-in-your-ide.rst
source/by-role/developer/index.rst
source/includes/content-retrieval-apis.rst
source/reference/index.rst
source/reference/modules/engine/configuration.rst

Update sidebar and fix broken link for search

Update sidebar and fix broken link for search

---

source/index.rst
source/reference/api/rest-content-retrieval-api.rst

Move reference section after by-role and fix broken link

Move reference section after by-role and fix broken link

---

source/contribute/acknowledgements.rst

Update OSS acknowledgements for 4.1.2

Update OSS acknowledgements for 4.1.2

---

source/by-role/developer/common/search.rst

Update example in search article

Update example in search article

---

source/by-role/system-admin/installation.rst
source/by-role/system-admin/performance-and-scaling/clustering.rst

Add note for ports in cluster

---

source/by-role/system-admin/configuration.rst

Add example for NGINX reverse proxy config

Add example for NGINX reverse proxy config

---

source/system-administrators/activities/reverse-proxy-configuration.rst

Add NGINX example for reverse proxy

[4.0] Add NGINX example

---

source/_static/theme/custom.css
source/by-role/developer/composable/index.rst
source/by-role/index.rst
source/contribute/index.rst
source/includes/formatting.rst

- Update links for marketplace in Sidebar
- Update links in Documentation by Role index file to go directly to the file when clicked from the Sidebar

Update links for marketplace in Sidebar

---

source/system-administrators/upgrade/index.rst
source/system-administrators/upgrade/upgrading-crafter.rst
source/system-administrators/upgrade/upgrading-mongodb.rst

Add upgrading MongoDB https://github.com/craftercms/craftercms/issues/6308

[4.0] Add upgrading MongoDB #6308

---

source/system-administrators/upgrade/index.rst
source/system-administrators/upgrade/upgrading-crafter.rst
source/system-administrators/upgrade/upgrading-mongodb.rst

Update upgrading MongoDB and fix warning https://github.com/craftercms/craftercms/issues/6308

[4.0] Update upgrading MongoDB and fix warning

---

source/developers/projects/engine/api/script-sandbox-configuration.rst

[3.1] Fix custom blacklist path

---

source/site-administrators/studio/permissions-mapping.rst
source/site-administrators/studio/role-mappings.rst
source/system-administrators/activities/security/configure-authentication-chain.rst
source/system-administrators/activities/security/configure-headers-based-auth.rst
source/system-administrators/activities/security/configure-password-requirements.rst
source/system-administrators/activities/security/configure-studio-saml.rst
source/system-administrators/activities/security/randomize-admin-passwd.rst

Update Studio header-based authentication https://github.com/craftercms/craftercms/issues/6414

[4.0] Update Studio header-based authentication #6414

---

source/by-role/developer/index.rst

Float the following core developer concepts in Sidebar:
- Content Modeling
- Information Architecture
- Content Inheritance
- Content Retrieval APIs
- Static Content Access
- Experience Builder
- Security
- Search

[docs] Float core developer concepts in Sidebar

---

source/by-role/developer/upgrade/index.rst
source/by-role/system-admin/upgrade/upgrading-search.rst

Update search upgrade notes https://github.com/craftercms/craftercms/issues/6462

Update search upgrade notes #6462

---

source/reference/modules/studio/configuration/user-interface-configuration.rst

Fix UI config missing SPA sources sidebar cabinet section

Fix UI config missing SPA sources sidebar cabinet section

---

source/by-role/developer/composable/extensions/plugin-host.rst

Fix "orphan" text rendering on page

Fix "orphan" text rendering on page

---

source/reference/api/templating-api.rst

Add escaping html and scripts section in templating API  https://github.com/craftersoftware/craftercms/issues/795

[master] Add escaping html and scripts section in templating API #795

---

source/by-role/developer/templated/templating.rst

Comment out empty sections in templating

Comment out empty sections in templating

---

source/developers/projects/engine/api/site/profile/set.rst

Update example response for Engine setProfile

Update example response for Engine setProfile

---

source/by-role/developer/composable/extensions/plugins.rst

Fix example for passing parameters to plugins https://github.com/craftercms/craftercms/issues/6574

Fix example for passing parameters to plugins #6574

---

source/reference/modules/studio/configuration/user-interface-configuration.rst

Fix typo in the PathNav widgets description https://github.com/craftercms/craftercms/issues/6570

Fix typo in the PathNav widgets description #6570

---

source/release-notes/4-1-3.rst

Add date for release

---

source/by-role/system-admin/performance-and-scaling/clustering.rst

Add status response for cluster node

---

source/by-role/system-admin/upgrade/index.rst
source/by-role/system-admin/upgrade/upgrading-server.rst

Update upgrading to read all release notes in between https://github.com/craftercms/craftercms/issues/6629

[master] Update upgrading to read all release notes in between #6629

---

source/by-role/developer/common/targeting.rst
source/reference/modules/studio/configuration/user-interface-configuration.rst

Update `Site Tools` mention to `Project Tools`

Update Site Tools mention to Project Tools

---

source/reference/modules/engine/configuration.rst
source/reference/modules/studio/configuration/index.rst
source/reference/modules/studio/configuration/project-policy-configuration.rst

Add note for project policy config https://github.com/craftercms/craftercms/issues/6525

Add note for project policy config #6525

---

source/by-role/system-admin/installation.rst

Update install requirements for MacOS

Update install requirements for MacOS

---

source/developers/extensions/blueprints.rst

Fix type case in passing parameters example in bp https://github.com/craftercms/craftercms/issues/6574

[4.0] Fix type case in passing parameters example in bp #6574

---

source/by-role/developer/composable/extensions/blueprints.rst

Fix type case in passing parameters example in bp https://github.com/craftercms/craftercms/issues/6574

[master] Fix type case in passing parameters example in bp #6574

---

source/release-notes/4-1-x-breaking-changes.rst

Add note on default item type for items under `/site` https://github.com/craftercms/craftercms/issues/6695

Add note on default item type for items under "/site" #6695

---

source/release-notes/4-0-x-breaking-changes.rst

Add note on default item type for items under `/site` https://github.com/craftercms/craftercms/issues/6695

[4.0] Add note on default item type for items under "/site" #6695

---

source/release-notes/4-1-4.rst

Update release date for 4.1.4

---

source/contribute/acknowledgements.rst

Update OSS acknowledgements for 4.1.4

Update OSS acknowledgements for 4.1.4

---

source/by-role/system-admin/upgrade/upgrading-cluster.rst

Update clustering upgrade doc https://github.com/craftercms/craftercms/issues/6607

Update clustering upgrade doc #6607

---

source/contribute/acknowledgements.rst

Update OSS acknowledgement for 4.1.5 release

Update OSS acknowledgement for 4.1.5 release

---

source/release-notes/4-1-3.rst
source/release-notes/4-1-x-breaking-changes.rst

Update release notes and breaking changes for 4.1.3 https://github.com/craftercms/craftercms/issues/6952

Update release notes and breaking changes for 4.1.3 #6952

---

source/by-role/system-admin/upgrade/upgrading-container.rst

Update upgrading docker compose instructions  https://github.com/craftercms/craftercms/issues/6132

Update upgrading docker compose instructions #6132

---

source/reference/modules/deployer/index.rst
source/reference/modules/engine/configuration.rst

Update configuration items to indicate location https://github.com/craftercms/craftercms/issues/6976

Update configuration items to indicate location #6976

---

source/by-role/system-admin/installation.rst

Add Image section in Docker https://github.com/craftercms/craftercms/issues/6781

Add docker image build #6781

---

source/by-role/developer/common/experience-builder.rst

Initilize XB manually with JavaScript  https://github.com/craftercms/craftercms/issues/6996

Initilize XB manually with JavaScript #6996

---

source/includes/request-groovy-variables.rst
source/reference/api/groovy-api.rst

Add example for pathVars https://github.com/craftercms/craftercms/issues/6602

Add example for pathVars #6602

---

source/by-role/system-admin/installation.rst

Update instructions for installing `libncurses5`  https://github.com/craftercms/craftercms/issues/7016

Update instructions for installing "libncurses5" #7016

---

source/by-role/developer/composable/extensions/plugins.rst

Fix mapping of scripts/classes in the plugins article https://github.com/craftercms/craftercms/issues/7166

Fix mapping scripts classes

---

source/conf.py
source/release-notes/4-1-6.rst
source/release-notes/index.rst

Add release notes for 4.1.6

---

source/release-notes/4-1-6.rst

Update release date for 4.1.6

---

source/contribute/acknowledgements.rst

Update OSS acknowledgements for 4.1.6

Update OSS acknowledgements for 4.1.6

---

source/reference/api/groovy-api.rst

Add new method writeContentAndNotify for Groovy scripts https://github.com/craftercms/craftercms/issues/7010

Add new write content and notify #7010

---

source/support.rst

Update support page for 4.1.6

---

source/reference/api/groovy-java-api.rst

Update subsection title under Groovy REST scripts https://github.com/craftercms/craftercms/issues/7223

Update subsection title under Groovy REST scripts #7223

---

source/by-role/system-admin/performance-and-scaling/clustering.rst

Add descriptions for the items displayed in the cluster tool  https://github.com/craftercms/craftercms/issues/7004

Updates to cluster screen

---

source/contribute/acknowledgements.rst

Update OSS acknowledgements for 4.1.8

Update OSS acknowledgements for 4.1.8

---

source/by-role/author/index.rst

Add anchor to RTE Code Samples section for ease of referencing section

Add anchor to RTE Code Samples section

---

source/_static/code/developer/xb/home.ftl
source/by-role/developer/common/experience-builder.rst

Add note for initializing XB for lazy loaded content https://github.com/craftercms/craftercms/issues/6970

Add note for initializing XB for lazy loaded content #6970

---

source/reference/modules/studio/configuration/index.rst

Add new property for setting Deployer HTTP requests timeout  https://github.com/craftercms/craftercms/issues/7331

Add new property for setting Deployer HTTP requests timeout #7331

---

source/conf.py
source/support.rst

Update bottom version picker and support page

[4.1] Update bottom version picker and support page

---

source/conf.py

[3.1] Update bottom version picker

---

source/by-role/common/crafter-cli.rst

Updates for Crafter CLI https://github.com/craftercms/craftercms/issues/6941 and https://github.com/craftercms/craftercms/issues/7153

Updates for Crafter CLI #6941

---

source/contribute/acknowledgements.rst

Update OSS acknowledgements for 4.2.0

Update OSS acknowledgements for 4.2.0

---

source/reference/modules/studio/configuration/rte-configuration.rst

Update RTE plugin template example https://github.com/craftersoftware/craftercms/issues/886

Update RTE plugin template example

---

source/_static/code/developer/SearchService.groovy
source/by-role/system-admin/upgrade/upgrading-search.rst

Update searchService references https://github.com/craftercms/craftercms/issues/6492

Update searchService references #6492

---

source/support.rst

[master] Update support page

---

source/by-role/system-admin/installation.rst

Update installation guide java version and libaio installation instruction

Update installation guide

---

source/conf.py
source/release-notes/4-1-9.rst
source/release-notes/index.rst
source/support.rst

Add release notes for 4.1.9

---

source/contribute/acknowledgements.rst

Update OSS acknowledgements for 4.1.9

Update OSS acknowledgements for 4.1.9

---

source/by-role/system-admin/installation.rst

Update instructions for installing libncurses5 in Ubuntu 24.04 https://github.com/craftercms/craftercms/issues/7016

Update instructions for installing libncurses5 in Ubuntu 24.04

---

source/conf.py
source/release-notes/index.rst
source/system-administrators/upgrade/index.rst

Update absolute links to relative

[3.1] Update absolute links to relative

---

source/conf.py
source/release-notes/index.rst
source/system-administrators/upgrade/index.rst

Update absolute links to relative

[4.0] Update absolute links to relative

---

source/by-role/system-admin/upgrade/index.rst
source/conf.py
source/release-notes/4-1-5.rst
source/release-notes/index.rst

Update absolute links to relative

[4.1] Update absolute links to relative

---

source/by-role/architect/index.rst

Pull in update from master to 4.1 for architect/index.rst (https://github.com/craftercms/docs/pull/1917)

Pull in update from master to 4.1 for architect/index.rst

---

source/developers/architecture.rst

Pull in update from master to 4.0 for developers/architecture.rst

Pull in update from master to 4.0 for developers/architecture.rst

---

source/by-role/system-admin/installation.rst
source/support.rst

[4.1] Update docs URL links

---

source/_ext/edit_on_github.py
source/by-role/system-admin/installation.rst
source/by-role/system-admin/upgrade/index.rst
source/release-notes/index.rst
source/support.rst

[master] Update docs URL links

---

source/_ext/edit_on_github.py
source/get-support/index.rst
source/getting-started/quick-start-guide.rst
source/release-notes/4-0-0.rst
source/system-administrators/activities/installing-craftercms-on-wsl2.rst

[4.0] Update docs URL links

---

source/by-role/system-admin/security/index.rst
source/conf.py
source/reference/api/groovy-java-api.rst

[4.1] Fix broken links

---

source/developers/extensions/plugin-host.rst
source/developers/extensions/resources/full-screen-plugin-example.rst
source/developers/extensions/resources/plugin-dashboard-example.rst
source/developers/extensions/resources/plugin-experience-builder-example.rst
source/developers/extensions/resources/plugin-navmenu-example.rst
source/developers/extensions/resources/plugin-projecttools-example.rst
source/developers/extensions/resources/plugin-sidebar-example.rst
source/developers/extensions/resources/plugin-toolbar-example.rst
source/developers/index.rst
source/developers/projects/engine/api/groovy-api.rst
source/system-administrators/activities/authoring/setup-authoring-using-aws-ami.rst
source/system-administrators/activities/delivery/setup-delivery-using-aws-ami.rst
source/system-administrators/activities/kubernetes/simple-delivery-kubernetes-deployment.rst

[4.0] Fix broken links

---

source/release-notes/4-2-x-breaking-changes.rst

Update breaking changes

---

source/reference/modules/studio/administration.rst

Enhance Studio access token docs https://github.com/craftercms/craftercms/issues/7601

Enhance Studio access token docs #7601

---

source/support.rst

[4.1] Update support page

---

source/by-role/developer/common/local-dev-with-docker.rst
source/getting-started/index.rst

Provide more appropriate wording around getting started running Crafter in Docker, so that it's clear that this one-line setup is great to TRY crafter, but developers should follow the documentation for developers.

Clarify Getting Started (Docker section)

---

source/by-role/developer/common/local-dev-with-docker.rst
source/getting-started/index.rst

Fix link to developers and warning

Fix link to developers

---

source/accessibility.rst
source/index.rst

Add accessibility https://github.com/craftercms/craftercms/issues/7660

Add accessibility #7660

---

source/accessibility.rst
source/index.rst

Add article on Accessibility https://github.com/craftercms/craftercms/issues/7660

[4.1] Add article on Accessibility #7660

---

source/reference/modules/engine/configuration.rst

Clean up comment and update engine custom properties https://github.com/craftercms/craftercms/issues/6896

Clean up comment and update engine custom properties

---

source/_static/theme/custom.css
source/_templates/page.html
source/conf.py

https://github.com/craftercms/craftercms/issues/8234

[4.0][8234] Add links to CrafterCMS's other products in docs

---

source/_static/theme/custom.css
source/_templates/page.html
source/conf.py

https://github.com/craftercms/craftercms/issues/8234

[3.1][8234] Add links to CrafterCMS's other products in docs

---

source/reference/api/groovy-java-api.rst

Update example for retrieving bean https://github.com/craftercms/craftercms/issues/8283

Update example for retrieving bean #8283
