- source/getting_started/index.rst
- source/includes/fact-databases.rst
- source/index.rst
- source/installation/guide_2.4.rst
- source/installation/guide_2.5.rst
- source/installation/index.rst
- source/release_notes/2.4.rst
- source/release_notes/2.5.rst
- source/release_notes/index.rst
- source/todo.rst
> Content updates

- source/products/studio/configure.rst
> Studio Configuration

- source/guides/admin/server-setup.rst
add session timeout configuration to detailed setup guide
> add session timeout configuration to detailed setup guide

- source/includes/installing-craftercms-locally-from-zip.rst
This is not yet complete but want to get some basic instructions up along with a video for installing from Zip that can be included where needed.
> Add initial include on installing from Zip

- source/roadmap/index.rst
Looking at other industry examples with similar documentation systems and tools, roadmap is maintained in JIRA.
> Point to roadmap in JIRA

- source/includes/fact-browsers.rst
- source/includes/fact-containers.rst
- source/includes/fact-databases.rst
- source/includes/fact-jvms.rst
- source/includes/fact-repos.rst
- source/system-administrators/index.rst
- source/system-administrators/prod-environment/supported-platforms.rst
Added include fragments for support as well as a master document under sys admins
> Added supported platforms

- source/content-authors/index.rst
- source/developers/cook-books/activiti/index.rst
- source/developers/cook-books/activiti/start-a-process.rst
- source/developers/cook-books/index.rst
- source/developers/index.rst
- source/release-notes/2-5-1.rst
small fixes
moving auth guide further
added dev cookbooks, with simple activiti tutorial
> small fixes, added cookbook, added simple activiti cookbook

- source/developers/cook-books/activiti/start-a-process.rst
- source/system-administrators/debugging-deployment.rst
fix formatting
add enterprise url to example in cookbook
> tiny fixes

- source/content-authors/index.rst
- source/developers/cook-books/index.rst
- source/developers/index.rst
- source/get-support/index.rst
- source/introduction/getting-started.rst
- source/system-administrators/dev-environment/install-from-zip.rst
- source/system-administrators/index.rst
updated support page
updated getting started
added some labels to pages we want to links to
> adding basics for support, getting started

- source/system-administrators/debugging-deployment.rst
> Debugging Deployment

- source/developers/projects/studio/source-code.rst
> Studio source code link

- source/system-administrators/rebuilding-studio-database.rst
Rebuild Studio Database document
> Rebuild Studio Database

- source/system-administrators/index.rst
- source/system-administrators/prod-environment/turning-off-show-error.rst
add article on turning off the show error in the FTLs
> add article on turning off the show error in the FTLs

- source/developers/cook-books/active-cache/cache-a-restful-response.rst
- source/developers/cook-books/active-cache/index.rst
- source/developers/cook-books/index.rst
Example show leveraging active cache to create a resultful service that returns data based on the response of an external service.
> create cookbook for active cache

- source/developers/cook-books/content-queries/basic-query-mechanics.rst
- source/developers/cook-books/content-queries/index.rst
- source/developers/cook-books/index.rst
Todo: Structure query in groovy
> cook book for querying content. Cover all 3 query types

- source/developers/cook-books/content-queries/basic-query-mechanics.rst
- source/developers/cook-books/services/get-a-list-of-sites.rst
- source/developers/cook-books/services/get-site-pages.rst
- source/developers/cook-books/services/index.rst
Add cookbooks for getting a list of sites and pages via REST
> Add cookbooks for getting a list of sites and pages via REST

- source/developers/cook-books/content-queries/basic-query-mechanics.rst
- source/index.rst
- source/upgrade/2-5-0-to-2-5-1.rst
- source/upgrade/index.rst
Add filter example to query cook book		
add version to version UPGRADE impact/instructions
> Add version to version upgrade log and added an example to a cookbook

- source/projects/studio/configuration/index.rst
- source/projects/studio/configuration/notifications.rst
- source/projects/studio/index.rst
- source/site-administrators/studio-configuration.rst
- source/site-administrators/studio/configure-notifications.rst
- administrator guide
- site admin guide
> add documentation on configuring notifications for studio workflow

- source/roadmap/index.rst
Was looking at issues, now pointing to GitHub
> Correct pointer to road map

- source/system-administrators/index.rst
- source/system-administrators/prod-environment/backup-and-recovery.rst
- source/system-administrators/tmp/backup-and-recovery.rst
Based on Wiki article
http://wiki.craftercms.org/display/CRAFTER/2.5.x+Installation#id-2.5.xInstallation-SettingupHotBackup
> port existing backup article

- source/release-notes/2-5-1.rst
- source/release-notes/2-5-2.rst
- source/release-notes/index.rst
* remove wiki link in 2.5.1 notes
* add 2.5.2 release notes
> add 2.5.2 release notes

- source/system-administrators/reindexing-content.rst
update document to match changes to rest API
Update content with index and other metadata
> Updates to Reindexing documentation

- source/system-administrators/reindexing-content.rst
Update document to match changes to rest API
Update content with index and other metadata
> Update reindex documentation

- source/system-administrators/prod-environment/install-studio.rst
Steps reference a database but there needs to be context provided so that the person doing the install understands the steps
> Provide some context for installation.

- source/system-administrators/prod-environment/install-deployment-agent.rst
Studio documentation
Install deployment agent
> Studio documentation

- source/developers/projects/studio/api/user-management/get-user.rst
Updated Get User to show a better example.
> User Management API

- source/developers/projects/studio/api/group-management/get-groups-per-site.rst
- source/developers/projects/studio/api/index.rst
Updated get users per site to use the param name "site_id" for consistency.
Added get groups per site.
> User and Group API Updates

- source/developers/projects/studio/api/group-management/add-user.rst
- source/developers/projects/studio/api/group-management/create-group.rst
- source/developers/projects/studio/api/group-management/delete-group.rst
- source/developers/projects/studio/api/group-management/get-group.rst
- source/developers/projects/studio/api/group-management/get-groups-per-site.rst
- source/developers/projects/studio/api/group-management/get-groups.rst
- source/developers/projects/studio/api/group-management/remove-user.rst
- source/developers/projects/studio/api/group-management/update-group.rst
- source/developers/projects/studio/api/index.rst
- source/developers/projects/studio/api/user-management/change-password.rst
- source/developers/projects/studio/api/user-management/create-user.rst
- source/developers/projects/studio/api/user-management/delete-user.rst
- source/developers/projects/studio/api/user-management/disable-user.rst
- source/developers/projects/studio/api/user-management/forgot-password.rst
- source/developers/projects/studio/api/user-management/get-user-status.rst
- source/developers/projects/studio/api/user-management/get-users-per-site.rst
- source/developers/projects/studio/api/user-management/get-users.rst
- source/developers/projects/studio/api/user-management/set-password.rst
- source/developers/projects/studio/api/user-management/update-user.rst
Added forgot password.
Added change password.
Added set password.
Updated get groups per site to include the users per group to speed up the UI.
Updated all documentation to have better references.
Updated formatting to look better.
> User and Group Management

- source/release-notes/2-5-3.rst
- source/release-notes/index.rst
Add release notes for 2.5.3 to master.
> 2.5.3 routine maint release notes

- source/developers/content-modeling.rst
- source/system-administrators/reindexing-content.rst
Include best practices, reserved names and a note about indexing.
> Add additional information about variable names

- source/release-notes/2-5-5.rst
> 2.5.5 release notes

- source/developers/index.rst
- source/developers/projects/commons/index.rst
- source/developers/projects/craftercms/index.rst
Added Crafter Commons.
Added CrafterCMS parent project - still a work in progress.
> Updated Crafter Module Documentation

- source/developers/projects/deployer/api/target-management/create-target.rst
Changed Create Target API doc to reflect the API changes done based on the new target templates.
> Changed Create Target API doc

- source/system-administrators/requirements-supported-platforms.rst
[docs] Getting Started: Requirements & Supported Platforms #508
> Complete Requirements & Supported Platforms section

- source/developers/projects/studio/api/group-management/get-groups-per-site.rst
- source/developers/projects/studio/api/group-management/get-users.rst
- source/developers/projects/studio/api/user-management/get-users-per-site.rst
- source/developers/projects/studio/api/user-management/get-users.rst
Updated range calls to have a "total" field.
> Studio API Updates

- source/developers/projects/studio/api/user-management/update-user.rst
Fixed missing ','
Ticket: https://github.com/craftercms/craftercms/issues/694
> CRAFTERCMS-694

- source/developers/projects/deployer/api/target-management/deploy-all-targets.rst
- source/developers/projects/deployer/api/target-management/deploy-target.rst
> API doc changes

- source/developers/search.rst
> Fixed typos in search documentation

- source/system-administrators/reindexing-content.rst
> Updated reindex documentation

- source/includes/how-search-works.rst
- source/system-administrators/debugging-search.rst
> Updated search debugging docs

- source/developers/projects/profile/api/access_token/delete.rst
- source/developers/projects/profile/api/authentication/authenticate.rst
- source/developers/projects/profile/api/authentication/persistent_login/create.rst
- source/developers/projects/profile/api/authentication/persistent_login/delete.rst
- source/developers/projects/profile/api/authentication/persistent_login/refresh_token.rst
- source/developers/projects/profile/api/authentication/ticket/create.rst
- source/developers/projects/profile/api/authentication/ticket/invalidate.rst
- source/developers/projects/profile/api/profile/change_password.rst
- source/developers/projects/profile/api/profile/create.rst
- source/developers/projects/profile/api/profile/delete.rst
- source/developers/projects/profile/api/profile/disable.rst
- source/developers/projects/profile/api/profile/enable.rst
- source/developers/projects/profile/api/profile/reset_password.rst
- source/developers/projects/profile/api/profile/update.rst
- source/developers/projects/profile/api/profile/verify.rst
- source/developers/projects/profile/api/tenant/attributes/remove.rst
- source/developers/projects/profile/api/tenant/delete.rst
- source/developers/projects/profile/api/tenant/roles/add.rst
- source/developers/projects/profile/api/tenant/roles/remove.rst
- source/developers/projects/profile/api/tenant/verify_new_profiles.rst
- source/developers/projects/search/api/search/v2/commit.rst
- source/developers/projects/search/api/search/v2/delete.rst
> Updates from feedback

- source/developers/projects/deployer/api/target-management/deploy-all-targets.rst
- source/developers/projects/deployer/api/target-management/deploy-target.rst
> Updated responses for deployment requests

- source/system-administrators/deployer/admin-guide.rst
- source/system-administrators/deployer/configuration-guide.rst
* Added Deployer Administration Guide.
> Deployer docs

- source/system-administrators/profile-admin/guides/tenants.rst
- source/system-administrators/profile-admin/index.rst
* Small fixes to Admin Console docs
> Profile Admin Console doc changes:

- source/system-administrators/prod-environment/configure-engine-multi-tenancy.rst
> Updated engine multi-tenancy docs

- source/system-administrators/index.rst
- source/system-administrators/profile/admin/index.rst
- source/system-administrators/profile/index.rst
- source/system-administrators/social/admin/index.rst
> Added Profile administration docs

- source/system-administrators/index.rst
- source/system-administrators/search/index.rst
- source/system-administrators/social/admin/guides/profiles.rst
> Added Search admin documentation

- source/system-administrators/profile/index.rst
- source/system-administrators/search/index.rst
* Did some quick fixes to Sys Admin doc for profile and search.
> Quick doc fixes:

- source/site-administrators/studio/permission-mappings.rst
- source/site-administrators/studio/role-mappings.rst
- source/system-administrators/upgrading-to-crafter-cms-3-0.rst
Added doc to upgrade Crafter CMS from 2.5.x to 3.0.
> Crafter 3.0 upgrade docs

- source/developers/projects/social/index.rst
- source/system-administrators/index.rst
- source/system-administrators/social/index.rst
> Added Social configuration docs.

- source/site-administrators/engine/engine-site-configuration.rst
> Updated Engine Site Configuration docs.

- source/system-administrators/profile/admin/guides/access_tokens.rst
* Renamed application name of default access tokens (fix for #1114).
> Profile access token docs:

- source/includes/how-search-works.rst
- source/system-administrators/debugging-search.rst
> Doc fixes:

- source/getting-started/quick-start-guide.rst
Add notes to run startup.bat the very first time as an administrator #1210
> Add notes to run startup.bat the very first time as an administrator 

- source/includes/installing-and-verifying-prerequisites.rst
Add note for older versions of windows may need to install update 2999226 Windows C runtime update #1232
> Add note for older versions of windows need to install update 2999226

- source/developers/projects/engine/api/templating-api.rst
- source/site-administrators/engine/engine-site-configuration.rst
> Improvements for templating API docs

- source/site-administrators/engine/engine-site-configuration.rst
> Added CORS example for site configuration file

- source/system-administrators/studio/debugging-publishing-issues.rst
Document how to fix publishing issues when upgrading Studio
Ticket:
https://github.com/craftercms/craftercms/issues/1314
> CRAFTERCMS-1314

- source/developers/projects/engine/api/templating-api.rst
- source/includes/freemarker-variables.rst
- source/includes/global-groovy-variables.rst
> Updated dynamic navigation docs

- source/developers/projects/studio/api/index.rst
Rename folder API - added page to index
Ticket
https://github.com/craftercms/craftercms/issues/1277
> CRAFTERCMS-1277

- source/system-administrators/studio/debugging-publishing-issues.rst
Debugging publishing issues article updates
Ticket:
https://github.com/craftercms/craftercms/issues/1207
> CRAFTERCMS-1207

- source/site-administrators/engine/engine-site-configuration.rst
> Fixed small error on sample config

- source/system-administrators/upgrade/upgrading-to-crafter-cms-3-0.rst
> Added new date format info for the upgrade guide

- source/developers/cook-books/setting-up-an-ldap-server-for-dev.rst
- source/system-administrators/studio/configure-ldap.rst
Update LDAP configuration docs to indicate multiple values are allowed for the siteId and group
> Update LDAP configuration docs to indicate multiple values are allowed..

- source/system-administrators/index.rst
- source/system-administrators/studio/exporting-importing-site.rst
- source/system-administrators/upgrade/upgrading-to-crafter-cms-3-0.rst
* Added instructions on how export/import a site.
> New Studio doc:

- source/system-administrators/upgrade/upgrading-to-crafter-cms-3-0.rst
> Updated date handling in the upgrade guide

- source/developers/projects/deployer/api/target-management/create-target.rst
> Updated deployer API docs

- source/system-administrators/setup-site-for-delivery.rst
> Updated delivery site setup guide

- source/system-administrators/deployer/debugging-deployer-issues.rst
- source/system-administrators/troubleshooting.rst
* Added Debugging Deployer Issues doc (fix for #1555).
>  Debugging Deployer Issues Doc:

- source/system-administrators/backup-and-recovery.rst
> Update backup and restore doc #1133

- source/system-administrators/studio/debugging-publishing-issues.rst
Removed recommendation to pull from sandbox to resolve publishing issues.
Ticket:
https://github.com/craftercms/craftercms/issues/1494
> CRAFTERCMS-1494

- source/system-administrators/backup-and-recovery.rst
Add to docs that when restoring the authoring environment, the delivery environment needs to be restored or re-init 
#1541
> Update restore documentation #1541

- source/system-administrators/index.rst
- source/system-administrators/security/randomize-admin-passwd.rst
> Add doc for randomizing admin password for a fresh install #1594

- source/developers/projects/craftercms/index.rst
- source/system-administrators/security/randomize-admin-passwd.rst
> Fix properties table in CrafterCMS gradle tool doc #1618

- source/developers/projects/studio/api/index.rst
https://github.com/craftercms/craftercms/issues/1601
> Added a note about CSRF token for Studio API docs

- source/release-notes/2-5-3.rst
> Fix warning on duplicate target for release notes

- source/developers/cook-books/best-practices/environment-specific-configurations.rst
- source/developers/cook-books/index.rst
https://github.com/craftercms/craftercms/issues/1573
> Added environment specific configuration cook-book

- source/system-administrators/deployer/admin-guide.rst
https://github.com/craftercms/craftercms/issues/1297
> Added proccesed-commits doc for the deployer

- source/faq/index.rst
> Update FAQ section

- source/_static/custom.css
- source/_static/custom.scss
https://github.com/craftercms/craftercms/issues/1663
> Additional visual distinctions to admonitions

- source/developers/cook-books/services/get-a-list-of-sites.rst
- source/developers/cook-books/services/get-site-pages.rst
- source/developers/cook-books/services/rendered-components-as-json.rst
> Fix typos and add linenos to sample code in cook-book/services #1675

- source/developers/projects/engine/api/site/profile/set.rst
https://github.com/craftercms/craftercms/issues/1671
> Added note about optional parameters in Engine API

- source/contribute/index.rst
- source/developers/projects/craftercms/index.rst
Update craftercms: Document `craftercms` cloning from `develop` if developer otherwise `master`#1677 and add a link to CONTRIBUTING.md in the `contribute` section of the docs
> Update craftercms doc on cloning for developer #1677

- source/release-notes/index.rst
Add link to release notes for 2.5.12 to index of releases page
> Add link to release notes for 2.5.12 to index of releases page

- source/developers/cook-books/services/rendered-components-as-json.rst
* Fixed "Rendered Page Components as JSON" example in docs. Also did some quick enhacements (craftercms/craftercms#1674)
> Fix for craftercms/craftercms#1674:

- source/developers/content-modeling.rst
Add cascade on delete configuration in content type and fix some formatting and typos
> Add cascade on delete configuration and fix some formatting and typos

- source/developers/projects/craftercms/index.rst
Update gradle task bundle creation mechanics #1712
> Update gradle task bundle creation mechanics #1712

- source/system-administrators/reindexing-content.rst
* Curl command had the wrong content type, fixed it to application/json.
> Command typo fix:

- source/release-notes/2-5-13.rst
- source/release-notes/index.rst
> Add release notes for 2-5-13

- source/getting-started/quick-start-guide.rst
- source/release-notes/2-5-13.rst
- source/release-notes/index.rst
Add release notes for 2-5-13 in the release note index
> Add release notes for 2-5-13 in the release note index

- source/developers/projects/studio/api/site/create-site.rst
Update parameter names to align with naming convention
https://github.com/craftercms/craftercms/issues/1725
> CRAFTERCMS-1725

- source/system-administrators/index.rst
- source/system-administrators/setup-site-for-delivery.rst
- source/system-administrators/studio/configure-headers-based-auth.rst
- Fix the port and host key algorithm to be used when using ssh for setting up your site for delivery
- Add configuration for headers based authentication #1715
> Update setup site for delivery and headers based authentication

- source/developers/projects/studio/api/publish/commits.rst
Add the missing closing bracket for the publish commits api example #1761
> Add the missing closing bracket for the publish commits api example

- source/release-notes/2-5-14.rst
- source/release-notes/index.rst
Update release notes for 2.5.14
> Update release notes for 2.5.14

- source/getting-started/index.rst
- source/getting-started/production-environment-setup.rst
- source/system-administrators/setup-site-for-delivery.rst
Add a guide on how to setup a production environment and update guide for setting up a site in delivery #1808
> Add a guide on how to setup a production environment #1808

- source/getting-started/production-environment-setup.rst
- source/getting-started/quick-start-guide.rst
- source/includes/installing-and-verifying-prerequisites.rst
Made some changes to production environment setup.
> Prod env setup

- source/release-notes/2-5-15.rst
- source/release-notes/index.rst
> Add release notes for 2.5.15

- source/developers/cook-books/index.rst
- source/developers/cook-books/marketplace/create-plugins.rst
- source/developers/cook-books/marketplace/index.rst
https://github.com/craftercms/craftercms/issues/1846
Please merge for 3.1+
> Added plugin-maker documentation

- source/upgrade/2-5-14-to-2-5-15.rst
- source/upgrade/index.rst
Add upgrade note for 2.5.14 to 2.5.15 #1858
> Add upgrade note for 2.5.14 to 2.5.15 #1858

- source/developers/testing.rst
- source/release-notes/3-0-7.rst
- source/release-notes/index.rst
Update release notes for 3.0.7
> Update release notes for 3.0.7

- source/developers/cook-books/best-practices/index.rst
- source/developers/cook-books/how-tos/index.rst
- source/developers/cook-books/how-tos/working-with-crafter-studios-api.rst
- source/developers/cook-books/index.rst
- source/release-notes/index.rst
Add to cookbook working with Crafter Studio's API and re-organize how-tos and best-practices
> Add to cookbook working with Crafter Studio's API and re-organize

- source/release-notes/3-0-8.rst
- source/release-notes/index.rst
Update release notes for 3.0.8
> Update release notes for 3.0.8

- source/system-administrators/upgrade/upgrading-to-craftercms-3-0.rst
* Added pre-requisites before running script.
* Added manual step of change parse date pattern.
Ticket craftercms/craftercms#1883
> Migration doc fixes:

- source/system-administrators/upgrade/upgrading-to-craftercms-3-0.rst
Update some formatting and text in upgrade doc #1844
> Update some formatting and text in upgrade doc #1844

- source/release-notes/index.rst
Update release notes title to fit with navigation titles
> Update release notes title to fit with navigation titles

- source/system-administrators/studio/debugging-publishing-issues.rst
Update some formatting and wording in debugging publishing issues
> Update some formatting and wording in debugging publishing issues

- source/system-administrators/activities/setup-site-for-delivery.rst
Add note that curl is required when running the init-site script for unix/linux
> Add note that curl is required when running the init-site script

- README.md
Update readme to remove install instruction for theme in docs #1892
> Update readme to remove install instruction for theme in docs #1892

- source/content-authors/index.rst
Update image sizes in content authors in 2.5
> Update image sizes in content authors in 2.5

- source/system-administrators/activities/setup-site-for-delivery.rst
Fix setup site for delivery #1916
> Fix setup site for delivery #1916

- source/site-administrators/studio/box-profiles-configuration.rst
Update Box Profiles Configuration to add <privateKey> field #1921
> Update Box Profiles Configuration to add <privateKey> field #1921

- source/developers/cook-books/how-tos/change-ports-on-your-install.rst
Fix path for file to change Solr port in How To Change the Ports on Your Crafter CMS Installation #1925
> Fix path for file to change Solr port in How To Change the Ports #1925

- source/release-notes/3-0-9.rst
- source/release-notes/index.rst
Update release notes for 3.0.9
> Update release notes for 3.0.9

- source/developers/projects/studio/api/index.rst
- source/developers/projects/studio/api/site/create-site.rst
Add new repo api's to toc and fix warning in create-site
> Add new repo api's to toc and fix warning in create-site

- source/developers/projects/engine/api/groovy-api.rst
* Added simple controller example that returns template path (fix for craftercms/craftercms#1951)
> Added simple controller example:

- source/developers/cook-books/how-tos/index.rst
- source/developers/cook-books/how-tos/using-war-overlays-with-crafter-engine.rst
Add article on using war overlays with crafter engine
> Add article on using war overlays with crafter engine

- source/developers/cook-books/how-tos/change-ports-on-your-install.rst
Update missing property when changin ports for MariaDB #1969
> Update missing property when changin ports for MariaDB #1969

- source/developers/in-context-editing.rst
Fix drag and drop section in in-context editing
> Fix drag and drop section in in-context editing

- source/developers/projects/studio/api/site/create-site.rst
Add clone from remote branch option with selecting single branch or all
https://github.com/craftercms/craftercms/issues/1987
> CRAFTERCMS-1987

- source/developers/content-modeling.rst
> Add doc for copy dependencies

- source/developers/content-modeling.rst
Add blurb for datasources used for paths of assets to be stored from ticket #1939
> Add blurb for datasources used for paths of assets to be stored

- source/system-administrators/activities/setup-site-for-delivery.rst
Add recommendation to use ssh in setup site for delivery #1918
> Add recommendation to use ssh in setup site for delivery #1918

- source/includes/installing-and-verifying-prerequisites.rst
Add note about lsof requirement for linux users
> Add note about lsof requirement for linux users

- source/getting-started/index.rst
- source/system-administrators/activities/production-environment-setup.rst
- source/system-administrators/index.rst
Add section on server hardware configuration consideration in setting up a production environment
> Add section on server hardware configuration consideration

- source/developers/cook-books/marketplace/create-plugins.rst
https://github.com/craftercms/craftercms/issues/1846
Please merge for 3.1
> Updated plugin maker doc with possible error messages

- source/system-administrators/activities/authoring-env-performance-tuning.rst
- source/system-administrators/activities/production-environment-setup.rst
- source/system-administrators/index.rst
Add article on authoring env performance tuning
> Add article on authoring env performance tuning

- source/system-administrators/activities/authoring-env-performance-tuning.rst
Fix warnings on authoring environment performance tuning
> Fix warnings on authoring environment performance tuning

- source/developers/developer-workflow/implementation-devops-workflow.rst
Some more updates for the implementation of devops workflow
> Some more updates for the implementation of devops workflow

- source/developers/projects/deployer/api/target-management/create-target.rst
* Added ssh_private_key_passphrase param to the Create Target API doc.
Ticket craftercms/craftercms#2079
> Added new param to Create Target API doc:

- source/conf.py
> Fix path for theme in conf.py

- source/developers/projects/qa/execution-with-maven.rst
> Fix warning message in 2.5

- source/developers/projects/marketplace/api/plugin-management/upload-plugin.rst
source/developers/projects/marketplace/api/plugin-management/upload-plugin.rst
> Fix the warning in upload_plugin.rst

- source/developers/form-controls/form-date-time.rst
Update date/time form control properties.
> Update date/time form control properties

- source/system-administrators/studio/studio-configuration-overrides.rst
Fix port numbers in the examples in the studio configuration overrides
>  Fix port numbers in the examples in the studio configuration overrides

- source/system-administrators/studio/debugging-publishing-issues.rst
Add note how to re-enable publishing after unblocking the queue #2112
> Add note how to re-enable publishing after unblocking the queue #2112

- source/developers/projects/engine/api/index.rst
- source/developers/projects/engine/api/site/cache/statistics.rst
https://github.com/craftercms/craftercms/issues/1999
> Added new api for getting cache statistics

- source/developers/projects/engine/api/site/cache/statistics.rst
https://github.com/craftercms/craftercms/issues/1999
> Updated example for new cache statistics API

- source/system-administrators/security/configure-ldap.rst
Update ldap configuration doc with regex for groupName
> Update ldap configuration doc with regex for groupName

- source/system-administrators/activities/setup-site-for-delivery.rst
Add note that git is required in authoring when using SSH in delivery #2172
> Add note that git is required in authoring when using SSH in delivery

- source/developers/content-modeling.rst
Add list of available macros for data sources #2179
> Add list of available macros for data sources #2179

- source/developers/projects/studio/api/repo/add-remote.rst
Fix the example in add remote api #2187
> Fix the example in add remote api #2187

- source/developers/form-controls/form-date-time.rst
Update property description of date/time control
> Update property description of date/time control

- source/site-administrators/studio/sidebar-configuration.rst
add additional detail to sidebar.xml documentation #2226
> add additional detail to sidebar.xml documentation #2226

- source/developers/projects/studio/api/workflow/submit-to-go-live.rst
Added environment parameter
https://github.com/craftercms/craftercms/issues/2202
> CRAFTERCMS-2202

- source/developers/projects/studio/api/workflow/submit-to-go-live.rst
- source/system-administrators/security/configure-headers-based-auth.rst
Update link and text for header based authentication configuration
> Update link and text for header based authentication configuration

- source/faq/index.rst
> Add some git questions in faq

- source/developers/projects/studio/api/workflow/get-go-live-items.rst
Added submitted to environment property to response
https://github.com/craftercms/craftercms/issues/2206
> CRAFTERCMS-2206

- source/developers/cook-books/blueprint/index.rst
- source/developers/developer-workflow/code-repo-n-devops-workflow.rst
- source/developers/developer-workflow/connecting-prod-cms-to-dev-workflow.rst
- source/developers/developer-workflow/developer-workflow.rst
- source/developers/developer-workflow/implementation-devops-workflow.rst
- source/developers/index.rst
- source/developers/projects/commons/index.rst
- source/developers/projects/core/index.rst
- source/developers/projects/craftercms/index.rst
- source/developers/projects/deployer/index.rst
- source/developers/projects/engine/index.rst
- source/developers/projects/profile/index.rst
- source/developers/projects/search/index.rst
- source/developers/projects/social/index.rst
- source/developers/projects/studio/api/repo/list-remote.rst
- source/developers/projects/studio/index.rst
- source/faq/index.rst
- source/getting-started/quick-start-guide.rst
- source/site-administrators/studio/rte-setup.rst
- source/source-code.rst
- source/system-administrators/activities/authoring-env-performance-tuning.rst
- source/system-administrators/activities/setup-site-for-delivery.rst
- source/system-administrators/deployer/admin-guide.rst
- source/system-administrators/studio/create-site-with-link-to-remote-repo.rst
- source/system-administrators/studio/debugging-publishing-issues.rst
- source/system-administrators/upgrade/upgrading-to-craftercms-3-0.rst
Update text to use "Git" instead of "git" where appropriate
> Update text to use "Git" instead of "git" where appropriate

- source/developers/projects/studio/api/index.rst
Add sync-staging to toc tree of Studio APIs
> Add sync-staging to toc tree of Studio APIs

- source/content-authors/content-authors-workflows.rst
- source/system-administrators/activities/production-environment-setup.rst
Update init-site script parameters listed and fix typo
> Update init-site script parameters listed and fix typo

- source/developers/cook-books/how-tos/index.rst
- source/developers/cook-books/how-tos/override-logging-levels.rst
- source/site-administrators/studio-logging.rst
Add how to override logging levels #2229
> Add how to override logging levels #2229

- source/system-administrators/index.rst
- source/system-administrators/upgrade/index.rst
> Add doc for upgrade script

- source/system-administrators/deployer/admin-guide.rst
> fileOutputProcessor now produces CSV files.

- source/system-administrators/deployer/admin-guide.rst
> Deployment pipeline requires gitDiffProcessor

- source/_static/custom.css
- source/_static/custom.scss
- source/system-administrators/index.rst
- source/system-administrators/studio/session-timeout-settings.rst
- source/system-administrators/upgrade/upgrading-to-craftercms-3-0.rst
Add tip to increase session timeout for very large sites #2264
> Add tip to increase session timeout for very large sites #2264

- source/system-administrators/requirements-supported-platforms.rst
Update supported Linux distros
> Update supported Linux distros

- source/system-administrators/deployer/admin-guide.rst
Add location of deployer config files
> Add location of deployer config files

- source/system-administrators/engine/configure-engine-single-tenant.rst
> Configuring single tenant should be documented.

- source/getting-started/quick-start-guide.rst
- source/includes/installing-and-verifying-prerequisites.rst
- source/system-administrators/activities/installing-and-verifying-prereq.rst
- source/system-administrators/engine/configure-engine-multi-tenancy.rst
- source/system-administrators/engine/configure-engine-single-tenant.rst
- source/system-administrators/index.rst
- source/system-administrators/requirements-supported-platforms.rst
Add configuring single tenant in engine and update sys admin layout, fix some spacing
> Add configuring single tenant in engine and update sys admin layout

- source/system-administrators/index.rst
Add configuring single tenant for engine to sys admin index
> Add configuring single tenant for engine to sys admin index

- source/system-administrators/activities/configure-apache-vhost.rst
- source/system-administrators/index.rst
add instructions for apache httpd configuration #2354
> add instructions for apache httpd configuration #2354

- source/site-administrators/studio/rte-setup.rst
Update RTE tiny mce plugins list
> Update RTE tiny mce plugins list

- source/site-administrators/studio/rte-setup.rst
Update RTE tiny mce plugins for 3.0
> Update RTE tiny mce plugins for 3.0

- source/developers/projects/studio/api/content/search.rst
- source/developers/projects/studio/api/content/set-item-state.rst
- source/developers/projects/studio/api/content/write-content.rst
Update example in write-content and fix typos in search and set-item-state #2457
> Update example in write-content and fix typos in other apis #2457

- source/developers/cook-books/how-tos/working-with-crafter-studios-api.rst
Update explanation of token #2458
> Update explanation of token #2458

- source/developers/projects/studio/api/content/search.rst
- source/developers/projects/studio/api/content/set-item-state.rst
- source/developers/projects/studio/api/content/write-content.rst
Update example in write-content and fix typos in other apis for master #2457
> Update example in write-content and fix typos in other apis for master

- source/system-administrators/security/configure-headers-based-auth.rst
- source/system-administrators/security/configure-ldap.rst
source/system-administrators/security/configure-ldap.rst
> Update config of ldap and headers #2417

- source/site-administrators/studio/aws-profiles-configuration.rst
Update sample profile for aws to include mediaconvert #2507
> Update sample profile for aws to include mediaconvert #2507

- source/site-administrators/studio/site-configuration.rst
Update site configuration description for 3.1
> Update site configuration description for 3.1

- source/site-administrators/studio/site-configuration.rst
Fix typo in site configuration
> Fix typo in site configuration

- source/system-administrators/index.rst
Update Java requirement listed for 3.0
> Update Java requirement listed for 3.0

- source/system-administrators/index.rst
Update Java requirement listed
> Update Java requirement listed

- source/system-administrators/activities/configure-apache-vhost.rst
Add lowercase rewrite rule #2382
> Add lowercase rewrite rule #2382

- source/system-administrators/activities/configure-apache-vhost.rst
Add lowercase rewrite rule for 3.0 #2382
> Add lowercase rewrite rule for 3.0 #2382

- source/system-administrators/activities/configure-solrcloud-for-crafter.rst
- source/system-administrators/index.rst
Add configure SolrCloud for Crafter #2414
> Add configure SolrCloud for Crafter #2414

- source/system-administrators/activities/delivery/change-ports-on-your-delivery-install.rst
Update changing ports in delivery to change the engine ports #2558
>  Update changing ports in delivery to change the engine ports #2558

- source/system-administrators/index.rst
- source/system-administrators/upgrade/upgrading-to-craftercms-3-1-0.rst
https://github.com/craftercms/craftercms/issues/2563
> Added upgrade docs for 3.1.0

- source/system-administrators/activities/delivery/change-ports-on-your-delivery-install.rst
- source/system-administrators/upgrade/index.rst
- source/system-administrators/upgrade/upgrading-to-craftercms-3-1-0.rst
- Update upgrade guide example
- Add to upgrade notes ldap/headers and groups membership changes #2417
- Fix typo in changing ports for delivery
> Update upgrade guide example

- source/release-notes/3-0-18.rst
- source/system-administrators/upgrade/index.rst
- source/system-administrators/upgrade/upgrading-from-craftercms-3-0-17.rst
> Update upgrade guide example for 3.0

- source/site-administrators/studio/aws-profiles-configuration.rst
Improve doc in example xml for aws profiles #2609
> Improve doc in example xml for aws profiles #2609

- source/site-administrators/studio/aws-profiles-configuration.rst
Update doc in xml for AWS profiles(master) #2609
> Update doc in xml for AWS profiles(develop) #2609

- source/developers/cook-books/content-queries/basic-query-mechanics.rst
During training with @russdanner, I found a few issues that addressing would improve the guide.
> Fixed Typo and Unnecessary reassignment of variable

- source/site-administrators/engine/engine-site-configuration.rst
> add note about error case in configuration

- source/developers/errors.rst
> add note concerning error conditions

- source/developers/errors.rst
- source/site-administrators/engine/engine-site-configuration.rst
Add note concerning error conditions and error case in configuration
Re:
PR https://github.com/craftercms/docs/pull/638 and 
PR https://github.com/craftercms/docs/pull/637
> Add note concerning error conditions and error case in configuration

- source/developers/cook-books/content-queries/basic-query-mechanics.rst
- source/developers/errors.rst
- source/site-administrators/engine/engine-site-configuration.rst
> Fix some typos

- source/developers/cook-books/how-tos/add-to-upgrade-scripts.rst
- source/developers/cook-books/how-tos/index.rst
Document how to add upgrade scripts to your customizations #2606
> Document how to add upgrade scripts to your customizations #2606

- source/developers/projects/engine/api/templating-api.rst
Add how to run scripts from Freemarker templates
> Add how to run scripts from Freemarker templates in 3.0

- source/developers/projects/engine/api/templating-api.rst
Add how to run scripts from Freemarker templates in master
> Add how to run scripts from Freemarker templates in master

- source/index.rst
- source/security/security-policies.rst
- source/system-administrators/index.rst
Move Security Policies to the top level for master #2633
> Move Security Policies to the top level for master #2633

- source/system-administrators/activities/security/configure-ldap.rst
Update ldap configuration wording for 3.0
> Update ldap configuration wording for 3.0

- source/system-administrators/activities/security/configure-ldap.rst
Update ldap configuration wording for master
> Update ldap configuration wording for master

- source/system-administrators/activities/authoring/change-ports-on-your-auth-install.rst
- source/system-administrators/index.rst
- source/system-administrators/studio/debugging-upgrade-issues.rst
Add debugging guide when studio upgrade fails #2656 and typo fix
> Add debugging guide when studio upgrade fails #2656 and typo fix

- source/developers/asset-processing.rst
Update asset processing for 3.0
> Update asset processing for 3.0

- source/developers/asset-processing.rst
Update asset processing for 3.1
> Update asset processing for 3.1

- source/includes/setup-ssh-keys.rst
- source/system-administrators/activities/delivery/setup-site-for-delivery.rst
- source/system-administrators/studio/create-site-with-link-to-remote-repo.rst
Update doc on ssh authentication #2717 for 3.0
> Update doc on ssh authentication #2717 for 3.0

- source/includes/setup-ssh-keys.rst
- source/system-administrators/activities/delivery/setup-site-for-delivery.rst
- source/system-administrators/studio/create-site-with-link-to-remote-repo.rst
Update doc on using ssh for auth #2717
> Update doc on using ssh for auth #2717

- source/includes/setup-ssh-keys.rst
- source/system-administrators/studio/create-site-with-link-to-remote-repo.rst
Fix RSA key documentation in Site Creation with Remote Repositories for 3.0 #2753
> Fix RSA key documentation in Site Creation with Remote Repositories for 3.0 #2753

- source/includes/setup-ssh-keys.rst
- source/system-administrators/studio/create-site-with-link-to-remote-repo.rst
Fix RSA key documentation in Site Creation with Remote Repositories #2753
> Fix RSA key documentation in Site Creation with Remote Repositories #2753

- source/developers/projects/deployer/api/target-management/create-target.rst
- source/developers/projects/studio/api/site/create-site.rst
Updated docs with new parameters for studio create site API and deployer create target API
https://github.com/craftercms/craftercms/issues/2759
> CRAFTERCMS-2759

- source/includes/installing-and-verifying-prerequisites.rst
Add note to install VS C++ redistributable if not installed for MongoDB to run for 3.0
> Add note to install VS C++ redistributable if not installed for MongoDB to run for 3.0

- source/includes/installing-and-verifying-prerequisites.rst
Add note to install VS C++ redistributable if not installed for MongoDB to run
> Add note to install VS C++ redistributable if not installed for MongoDB to run

- source/developers/cook-books/how-tos/change-log-data-folder-location.rst
- source/developers/cook-books/how-tos/index.rst
Add how to change default logs and data folder location for 3.0
> Add how to change default logs and data folder location for 3.0

- source/developers/cook-books/how-tos/change-log-data-folder-location.rst
- source/developers/cook-books/how-tos/index.rst
Add how to change default logs and data folder
> Add how to change default logs and data folder location

- source/system-administrators/upgrade/index.rst
Fix typo in upgrade doc for 3.0
> Fix typo in upgrade doc for 3.0

- source/system-administrators/upgrade/index.rst
> Fix typo in upgrade doc

- source/includes/installing-and-verifying-prerequisites.rst
Add to docs requirement for libncurses5 #2784
> Add to docs requirement for libncurses5 #2784

- source/system-administrators/studio/create-site-with-link-to-remote-repo.rst
> Fix typo #2753

- source/system-administrators/studio/create-site-with-link-to-remote-repo.rst
> Fix typo for 3.0 #2753

- source/system-administrators/upgrade/index.rst
Add note which compressed file archive to use depending on OS for 3.0 #2794
> Add note which compressed file archive to use depending on OS for 3.0 #2794

- source/system-administrators/upgrade/index.rst
Add note which compressed file archive to use depending on OS #2794
> Add note which compressed file archive to use depending on OS #2794

- source/release-notes/3-0-20.rst
Add missing file for release note for 3.0.20
> Add missing file for release note for 3.0.20

- source/release-notes/3-0-19.rst
- source/system-administrators/upgrade/upgrading-to-craftercms-3-0-19.rst
> Add upgrade notes for 3.0.19

- source/developers/cook-books/aws/use-s3-to-store-assets.rst
Fix typo in use s3 to store assets article in 3.0
> Fix typo in use s3 to store assets article in 3.0

- source/developers/cook-books/content-queries/basic-query-mechanics.rst
- source/developers/cook-books/how-tos/index.rst
- source/developers/cook-books/how-tos/migrate-site-to-elasticsearch.rst
- source/developers/projects/engine/api/index.rst
- source/developers/projects/engine/api/site/elasticsearch/search.rst
- source/developers/search-solr.rst
- source/includes/global-groovy-variables.rst
https://github.com/craftercms/craftercms/issues/2654
> Add documentation for new ElasticSearch API in Engine

- source/developers/content-modeling.rst
- source/developers/content-type-page.rst
- source/developers/cook-books/best-practices/best-practice-loading-content.rst
- source/developers/cook-books/how-tos/integrating-crafter-cms-with-bitbucket.rst
- source/developers/cook-books/how-tos/integrating-crafter-cms-with-github.rst
- source/developers/cook-books/how-tos/integrating-crafter-cms-with-gitlab.rst
- source/developers/developer-workflow/developer-workflow.rst
- source/developers/index.rst
- source/developers/projects/craftercms/index.rst
- source/includes/fact-databases.rst
- source/includes/how-search-works-solr.rst
- source/site-administrators/studio/content-monitoring.rst
- source/system-administrators/activities/authoring/authoring-env-performance-tuning.rst
- source/system-administrators/activities/authoring/change-ports-on-your-auth-install.rst
- source/system-administrators/activities/debugging-search-solr.rst
- source/system-administrators/activities/delivery/change-ports-on-your-delivery-install.rst
- source/system-administrators/activities/delivery/setup-site-for-delivery.rst
- source/system-administrators/activities/logging.rst
- source/system-administrators/activities/troubleshooting.rst
https://github.com/craftercms/craftercms/issues/2654
> Updates for Solr references in all docs

- source/developers/cook-books/how-tos/add-to-upgrade-scripts.rst
https://github.com/craftercms/craftercms/issues/2646
> Update documentation for upgrade operations

- source/developers/cook-books/content-queries/basic-query-mechanics.rst
> Remove real name in doc

- source/developers/cook-books/content-queries/basic-query-mechanics.rst
Remove real name in doc for 3.0
> Remove real name in doc for 3.0

- source/developers/projects/studio/api/cmis/upload.rst
Fix error in CMIS upload api doc
> Fix error in CMIS upload api doc

- source/developers/projects/studio/api/api-version1.rst
- source/developers/projects/studio/api/cmis/upload.rst
> Add to index cmis upload api

- source/developers/cook-books/box/use-box-to-store-assets.rst
- source/site-administrators/studio/aws-profiles-configuration.rst
- source/site-administrators/studio/box-profiles-configuration.rst
- source/site-administrators/studio/webdav-profiles-configuration.rst
Remove recommendation to encrypt passwords, etc. in configurations #2551
> Remove recommendation to encrypt passwords, etc. in configurations #2551

- source/developers/projects/studio/api/api-version1.rst
- source/developers/projects/studio/api/index.rst
> Update audit api v1 #2925

- source/site-administrators/studio/aws-profiles-configuration.rst
> Remove "$enc" in aws config

- source/site-administrators/studio/aws-profiles-configuration.rst
- source/site-administrators/studio/box-profiles-configuration.rst
- source/site-administrators/studio/webdav-profiles-configuration.rst
Remove recommendation to encrypt passwords in config files
> Remove recommendation to encrypt passwords in config files

- source/includes/setup-ssh-keys.rst
- source/system-administrators/activities/debugging-ssh-issues.rst
- source/system-administrators/activities/troubleshooting.rst
- source/system-administrators/index.rst
- source/system-administrators/studio/create-site-with-link-to-remote-repo.rst
Add note that passphrase is not supported for ssh key for master
> Add note that passphrase is not supported for ssh key for master

- source/developers/index.rst
- source/developers/projects/docker-compose/index.rst
Add Crafter CMS Docker Compose to subsystems #3023
> Add Crafter CMS Docker Compose to subsystems #3023

- source/developers/cook-books/how-tos/change-log-data-folder-location.rst
- source/developers/projects/craftercms/index.rst
- source/getting-started/quick-start-guide.rst
- source/includes/installing-and-verifying-prerequisites.rst
- source/includes/installing-craftercms-locally-from-zip.rst
- source/system-administrators/activities/authoring/change-ports-on-your-auth-install.rst
- source/system-administrators/activities/backup-and-recovery.rst
- source/system-administrators/activities/delivery/change-ports-on-your-delivery-install.rst
- source/system-administrators/activities/delivery/setup-site-for-delivery.rst
- source/system-administrators/activities/installing-and-verifying-prereq.rst
- source/system-administrators/upgrade/index.rst
Update docs on windows support #2961
> Update docs on windows support #2961

- source/system-administrators/activities/logging.rst
https://github.com/craftercms/craftercms/issues/2904
> Update logging documentation

- source/developers/projects/studio/api/site/create-site.rst
https://github.com/craftercms/craftercms/issues/3033
> Remove 'search_engine' parameter

- source/developers/projects/social/api/index.rst
https://github.com/craftercms/craftercms/issues/3052
> Fix authentication note for crafter social

- source/includes/upgrading-to-solr-7.rst
- source/system-administrators/upgrade/upgrading-to-craftercms-3-0-21.rst
https://github.com/craftercms/craftercms/issues/2654
> Update upgrade notes for Solr changes

- source/index.rst
> Fix typo and suggestions

- source/system-administrators/activities/debugging-search-elasticsearch.rst
> Update based on review #2830

- source/system-administrators/activities/reindexing-content-in-prod.rst
- source/system-administrators/activities/reindexing-content.rst
https://github.com/craftercms/craftercms/issues/3080
> Updated search reindex guides to include Elasticsearch

- source/craftercms_sphinx_theme/breadcrumbs.html
- source/craftercms_sphinx_theme/layout.html
- source/craftercms_sphinx_theme/static/css/app.css
Updates on ugrading to 3.1 #2699
> Updates on ugrading to 3.1 #2699

- source/developers/cook-books/how-tos/migrate-site-to-elasticsearch.rst
https://github.com/craftercms/craftercms/issues/3034
> Improve Elasticsearch site migration guide

- source/includes/upgrading-to-solr-7.rst
- source/system-administrators/upgrade/upgrading-to-craftercms-3-1-0.rst
> Fixed upgrade to 3.1.0 docs

- source/contribute/documentation-template.rst
- source/craftercms_sphinx_theme/layout.html
- source/system-administrators/upgrade/upgrading-to-craftercms-3-1-0.rst
Updates to upgrading to 3.1 #2699
- fix for is-up-to-date flag
- updates for dependency resolver configuration when updating
- updates to documentation standard for images
> Updates to upgrading to 3.1 #2699

- source/system-administrators/upgrade/upgrading-to-craftercms-3-1-0.rst
Update note on dependency resolver configuration file #2699
> Update note on dependency resolver configuration file #2699

- source/system-administrators/upgrade/upgrading-to-craftercms-3-1-0.rst
Some more updates on instructions for upgrading to 3.1 to update the paths in the deployer targets
> Some more updates on instructions for upgrading to 3.1

- source/release-notes/3-1-0.rst
- source/release-notes/index.rst
- source/system-administrators/upgrade/upgrading-to-craftercms-3-1-0.rst
> Add release notes for 3.1.0

- source/developers/cook-books/graphql/index.rst
* Added alias examples.
* Added more examples and fixed some of the doc.
Ticket craftercms/craftercms#3083
> GraphQL doc fixes:

- source/developers/cook-books/graphql/index.rst
https://github.com/craftercms/craftercms/issues/2970
https://github.com/craftercms/craftercms/issues/3145
> Improve GraphQL examples

- source/developers/projects/studio/api/site/create-site.rst
Update blueprint parameter in Create Site example.
> Update blueprint name in example

- source/system-administrators/activities/production-environment-setup.rst
Update based on comment for Set Profile Cookies to Secure #3047
> Update based on comment for Set Profile Cookies to Secure #3047

- source/developers/form-controls/form-date-time.rst
- source/system-administrators/activities/debugging-search-elasticsearch.rst
Add notice about Elasticsearch monitoring #3029
Update form date-time control populate expression #2648
> Updates for Elasticsearch monitoring and form date-time control

- source/developers/cook-books/how-tos/migrate-site-to-elasticsearch.rst
https://github.com/craftercms/craftercms/issues/3185
> Update elasticsearch migration guide

- source/system-administrators/upgrade/index.rst
Remove content/add note about the --full flag in upgrades #3194
> Remove content/add note about the --full flag in upgrades #3194

- source/system-administrators/upgrade/index.rst
Remove content/add note about the --full flag in upgrades #3194
> Remove content/add note about the --full flag in upgrades for 3.0 #3194

- source/system-administrators/upgrade/index.rst
Remove other mentions of full upgrade #3197
> Remove other mentions of full upgrade #3197

- source/developers/projects/craftercms/index.rst
- source/system-administrators/upgrade/index.rst
Update craftercms scripts doc and fix warning for 3.0
> Update craftercms scripts doc and fix warning for 3.0

- source/developers/projects/craftercms/index.rst
Update CrafterCMS scripts doc #3097
> Update CrafterCMS scripts doc #3097

- source/developers/extending-studio/build-a-data-source.rst
- source/developers/extending-studio/form-engine-control.rst
Update locations for building datasources and controls for 3.0 #3220
> Update locations for building datasources and controls for 3.0 #3220

- source/site-administrators/studio/sidebar-configuration.rst
This fixes the docs to have the correct way of editing icons in sidebar
> updated the way to change icons of the sidebar

- source/system-administrators/deployer/processors-guide.rst
- source/system-administrators/index.rst
https://github.com/craftercms/craftercms/issues/2954
> Add a guide about Deployer processors

- source/system-administrators/activities/security/configure-ldap.rst
https://docs.craftercms.org/en/3.1/system-administrators/activities/security/configure-ldap.html
> Update ldap port

- source/developers/cook-books/how-tos/migrate-site-to-elasticsearch.rst
https://github.com/craftercms/craftercms/issues/3291
Also fixed some syntax issues
> Update for elasticsearch migration doc

- source/developers/projects/studio/api/site/create-site.rst
Add authentication_type to example and notes in create-site api #3307
> Add authentication_type to example and notes in create-site api #3307

- source/developers/projects/studio/api/site/create-site.rst
Add authentication_type to example and notes in create-site api for 3.0 #3307
> Add authentication_type to example and notes in create-site api for 3.0 #3307

- source/site-administrators/studio/mime-types-configuration.rst
Update mime type configuration #3275
> Update mime type configuration #3275

- source/system-administrators/activities/delivery/delivery-env-performance-tuning.rst
- source/system-administrators/index.rst
Add a tuning page for delivery environment #2949
> Add a tuning page for delivery environment #2949

- source/system-administrators/activities/delivery/delivery-env-performance-tuning.rst
- source/system-administrators/index.rst
Add delivery environment performance tuning for 3.0 #2949
> Add delivery environment performance tuning for 3.0 #2949

- source/system-administrators/deployer/processors-guide.rst
https://github.com/craftercms/craftercms/issues/3347
> Update doc with new property

- source/conf.py
Update swaggerhub api version to 3.1.1.16
> Update swaggerhub api version to 3.1.1.16

- source/system-administrators/deployer/templates-guide.rst
- source/system-administrators/index.rst
https://github.com/craftercms/craftercms/issues/3276
> Add guide for Crafter Deployer target templates

- source/_static/code/kubernetes/simple/authoring-deployment.yaml
- source/_static/code/kubernetes/simple/delivery-deployment.yaml
Update docker images versions in Kubernetes tutorial with the latest release
> Update docker images versions in kubernetes tutorial

- source/conf.py
- source/developers/projects/craftercms/index.rst
- source/system-administrators/upgrade/index.rst
Update upgrade guide
Remove the message at the top of the doc sidebar
Fix typo in overwrite config description
> Update upgrade guide and fix typo  #3097

- source/system-administrators/index.rst
- source/system-administrators/upgrade/upgrading-to-craftercms-3-1-0.rst
Remove reference to missing file #3418
> Remove reference to missing file #3418

- source/conf.py
Update swaggerhub Studio API version pointed to
> Update swaggerhub Studio API version pointed to

- source/_static/code/kubernetes/simple/authoring-deployment.yaml
- source/_static/code/kubernetes/simple/delivery-deployment.yaml
- source/_static/code/kubernetes/simple/elasticsearch-deployment.yaml
Ticket craftercms/craftercms#3447
> Update simple Kubernetes configs.

- source/system-administrators/studio/create-site-with-link-to-remote-repo.rst
- source/system-administrators/upgrade/index.rst
- source/system-administrators/upgrade/upgrading-to-craftercms-3-1-0.rst
* Add note that a Studio restart is required for default SSH keys to get picked up #3460
* Fix warnings of undefined labels
> Add note that a Studio restart is required for default SSH keys to get picked up #3460

- source/release-notes/3-1-3.rst
- source/system-administrators/upgrade/upgrading-to-craftercms-3-1-3.rst
Add upgrade notes for Docker/Kuber deployments #3457
> Add upgrade notes for Docker/Kuber deployments #3457

- source/system-administrators/studio/create-site-with-link-to-remote-repo.rst
Add note that a Studio restart is required for default SSH keys to get picked up in 3.0 #3460
> Add note that a Studio restart is required for default SSH keys to get picked up in 3.0 #3460

- source/conf.py
Update swaggerhub api 2 versions links
> Update swaggerhub api 2 versions links

- source/developers/projects/studio/api/api-version1.rst
- source/developers/projects/studio/api/aws/mediaconvert/post-upload.rst
- source/developers/projects/studio/api/aws/s3/post-upload.rst
- source/developers/projects/studio/api/cmis/clone.rst
- source/developers/projects/studio/api/cmis/list.rst
- source/developers/projects/studio/api/cmis/search.rst
- source/developers/projects/studio/api/cmis/upload.rst
- source/developers/projects/studio/api/repo/add-remote.rst
- source/developers/projects/studio/api/repo/list-remote.rst
- source/developers/projects/studio/api/repo/pull-from-remote.rst
- source/developers/projects/studio/api/repo/push-to-remote.rst
- source/developers/projects/studio/api/repo/rebuild-database.rst
- source/developers/projects/studio/api/repo/remove-remote.rst
Mark API 1 that are now deprecated
> Mark API 1 that are now deprecated

- source/getting-started/quick-start-guide.rst
- source/system-administrators/activities/production-environment-setup.rst
Update archive file names used in quick start guide and production environment setup for 3.0  #3473
> Update archive file names used in quick start guide and production environment setup for 3.0  #3473

- source/developers/projects/studio/api/site/create-site.rst
> Add doc for blueprint parameters

- source/getting-started/quick-start-guide.rst
Update file names for deployable bundle being built #3473
> Update file names for deployable bundle being built #3473

- source/developers/form-sources/form-source-embedded-content.rst
Add file for embedded content datasource #3392
> Add file for embedded content datasource #3392

- source/developers/remote-assets.rst
Add text for bypassing of /remote-assets for webDAV in delivery #3420
> Add text for bypassing of /remote-assets for webDAV in delivery #3420

- source/conf.py
- source/system-administrators/deployer/processors-guide.rst
- Fix typos in git push processor properties #3502
- Update swagger API version
> Fix typos in git push processor properties #3502

- source/developers/projects/studio/api/site/create-site.rst
Add 'Create site as orphan' option to Create Site API
https://github.com/craftercms/craftercms/issues/3515
> CRAFTERCMS-3515

- source/system-administrators/activities/clustering.rst
Add more description on node communication in clustering and update MariaDB version required
> Add more description on node communication in clustering and update MariaDB version required

- source/conf.py
Update swaggerhub api version to 3.1.4.6
> Update swaggerhub api version to 3.1.4.6

- source/developers/cook-books/how-tos/web-app-manifest-use-credentials.rst
Updates to web app manifest use based on review #3450
> Updates to web app manifest use based on review #3450

- source/developers/content-modeling.rst
- source/site-administrators/engine/engine-site-security-guide.rst
Update reserved variable names and add warning to engine site security guide for variable names
> Update reserved variable names and add warning to engine site security guide for variable names

- source/developers/cook-books/how-tos/web-app-manifest-use-credentials.rst
> Fix wrong grammar #3450

- source/developers/cook-books/blueprint/index.rst
Add image size recommendation for bp screenshots for craftercms-plugin.yaml file
> Add image size recommendation for bp screenshots for craftercms-plugin.yaml file

- source/developers/in-context-editing.rst
Add parent tag to to renderComponent macro
> Add parent tag to to renderComponent macro

- source/developers/cook-books/blueprint/index.rst
Update passing parameter to bp based on review #3002
> Update passing parameter to bp based on review #3002

- source/developers/developer-workflow/implementation-prod-repo-sync.rst
Fix incorrect reference to code forward content back #3650
> Fix incorrect reference to code forward content back #3650

- source/developers/developer-workflow/implementation-prod-repo-sync.rst
Fix incorrect reference to code forward content back for 3.0 #3650
> Fix incorrect reference to code forward content back for 3.0 #3650

- source/system-administrators/deployer/processors-guide.rst
Update git push processor parameters - add `pushAll` and `force` parameter
> Update git push processor parameters

- source/developers/cook-books/marketplace/create-plugins.rst
- source/developers/cook-books/marketplace/index.rst
Update articles to use Crafter Marketplace and fix typo in image display
> Update articles to use Crafter Marketplace and fix typo in image display

- source/system-administrators/activities/security/configure-password-requirements.rst
Fix warning in configuring password requirements
> Fix warning in configuring password requirements

- source/developers/in-context-editing.rst
Update @studio.componentContainerAttr and @studio.componentAttr attributes
> Update @studio.componentContainerAttr and @studio.componentAttr attributes

- source/system-administrators/deployer/templates-guide.rst
Ticket craftercms/craftercms#3692
> Fixed Deployer templates guide

- source/system-administrators/upgrade/upgrading-to-craftercms-3-1-4.rst
Update upgrading guide for ice macro/attributes update
> Update upgrading guide for ice macro/attributes update

- source/developers/in-context-editing-ftl.rst
- source/developers/in-context-editing.rst
Update attributes used for in-context editing
> Update attributes used for in-context editing

- source/developers/cook-books/how-tos/migrate-site-to-elasticsearch.rst
Add instruction to add searchEngine: Elasticsearch in guide for updating Solr to Elasticsearch
> Add instruction to add searchEngine: Elasticsearch in guide for updating Solr to Elasticsearch

- source/site-administrators/engine/engine-site-configuration.rst
- source/system-administrators/activities/encrypting-configuration-properties.rst
- source/system-administrators/index.rst
https://github.com/craftersoftware/craftercms/issues/18
> Update documentation for encrypted configuration properties

- source/system-administrators/deployer/elasticsearch-configuration-guide.rst
- source/system-administrators/index.rst
https://github.com/craftercms/craftercms/issues/3761
> Add documentation for using multiple Elasticsearch clusters

- source/developers/cook-books/marketplace/create-plugins.rst
Add note to make repo public when creating plugin for marketplace
> Add note to make repo public when creating plugin for marketplace

- source/developers/projects/engine/api/site/cache/clear.rst
- source/developers/projects/engine/api/site/context/graphql/rebuild.rst
- source/developers/projects/engine/api/site/context/rebuild.rst
> Update Engine response messages

- source/system-administrators/activities/security/configure-authentication-chain.rst
- source/system-administrators/activities/security/configure-studio-saml.rst
- source/system-administrators/activities/security/configure-studio-security.rst
Document Studio SAML2 Configuration
> Document Studio SAML2 Configuration

- source/system-administrators/upgrade/index.rst
Update sequence when upgrading from a new bundle
> Update sequence when upgrading from a new bundle

- source/developers/cook-books/graphql/custom-graphql-schema.rst
- source/developers/cook-books/how-tos/add-to-upgrade-scripts.rst
- source/site-administrators/studio/rte2-setup.rst
- source/system-administrators/activities/configure-solrcloud-for-crafter.rst
> Update broken links

- source/system-administrators/upgrade/upgrading-to-craftercms-3-1-5.rst
> Adding instructions for Docker upgrade to 3.1.5

- source/site-administrators/encrypting-text-in-config.rst
- source/system-administrators/activities/encrypting-configuration-properties.rst
Update encryption tool based on review
> Update encryption tool based on review

- source/release-notes/3-1-5.rst
Add link on how to upgrade docker installs from 3.1.4 to 3.1.5
> Add link on how to upgrade docker installs from 3.1.4 to 3.1.5

- source/release-notes/3-1-5.rst
Add to release notes upgraded tomcat version to 8.5.51
> Add to release notes upgraded tomcat version to 8.5.51

- source/system-administrators/index.rst
- source/system-administrators/upgrade/docker/config/config-changes-3.1.4-to-3.1.5.rst
- source/system-administrators/upgrade/docker/config/index.rst
- source/system-administrators/upgrade/docker/index.rst
- source/system-administrators/upgrade/index.rst
> Updated Docker/Kuber upgrade instructions

- source/release-notes/3-1-5.rst
Update link to updating docker/kuber installs in release notes
> Update link to updating docker/kuber installs in release notes

- source/system-administrators/activities/authoring/main-menu-global-config.rst
- source/system-administrators/activities/security/configure-authentication-chain.rst
- source/system-administrators/activities/security/configure-headers-based-auth.rst
- source/system-administrators/studio/studio-configuration-overrides.rst
Update headers based authentication text/comments
> Update headers based authentication text/comments

- source/acknowledgements/index.rst
- source/conf.py
- source/index.rst
Add page for acknowledgements
Add ignore list for link checking
Update swagger api version
> Add page for acknowledgements

- source/system-administrators/activities/autoclustering-with-studio.rst
https://github.com/craftersoftware/craftercms/issues/65
Depends on https://github.com/craftersoftware/studio-arbiter/pull/3
> Update studio arbiter docs

- source/site-administrators/engine/engine-site-configuration.rst
Add cache warm up properties to engine site configuration
> Add cache warm up properties to engine site configuration

- source/site-administrators/studio/rte2-setup.rst
Add note that rte only supports lowercase for custom elements
> Add note that rte only supports lowercase for custom elements

- source/developers/cook-books/marketplace/index.rst
> Add marketplace link

- source/system-administrators/activities/autoclustering-with-studio.rst
> Fixed documentation for Studio auto-cluster.

- source/includes/freemarker-variables.rst
- source/includes/request-groovy-variables.rst
- Include new variable authToken
- Add note about profile & authentication
https://github.com/craftersoftware/craftercms/issues/86
> Update groovy & freemarker variables:

- source/site-administrators/engine/engine-saml2-configuration.rst
> Update SAML2 configuration

- source/developers/cook-books/best-practices/environment-specific-configurations.rst
- source/developers/projects/craftercms/index.rst
- source/site-administrators/studio/multi-environment-configurations.rst
Use CRAFTER_ENVIRONMENT to set active environment
> Use CRAFTER_ENVIRONMENT to set active environment

- source/developers/projects/engine/api/site/elasticsearch/search.rst
https://github.com/craftercms/craftercms/issues/3978
> Fix response format for Elasticsearch API

- source/system-administrators/deployer/processors-guide.rst
Update deployer command line processors #3927
> Update deployer command line processors #3927

- source/developers/projects/engine/api/access-to-services.rst
- source/includes/freemarker-variables.rst
- source/includes/request-groovy-variables.rst
- Restricted variables & how to disable it
https://github.com/craftersoftware/craftercms/issues/85
> Document new configuration:

- source/system-administrators/upgrade/docker/config/config-changes-3.1.5-to-3.1.6.rst
- source/system-administrators/upgrade/docker/config/index.rst
> Added config files differences from 3.1.5 to 3.1.6

- source/site-administrators/engine-configuration.rst
- source/site-administrators/engine/engine-crafter-profile-configuration.rst
- source/site-administrators/engine/engine-saml2-configuration.rst
- source/site-administrators/engine/engine-site-security-guide.rst
https://github.com/craftercms/craftercms/issues/3992
Please merge for 3.1 too
> Updates for Site Security docs

- source/includes/setup-ssh-keys.rst
- source/system-administrators/activities/debugging-ssh-issues.rst
- source/system-administrators/activities/kubernetes/simple-kubernetes-deployment.rst
Add other OS needing pem option when generating keys #3719
> [master] Add other OS needing pem option when generating keys #3719

- source/includes/setup-ssh-keys.rst
- source/system-administrators/activities/debugging-ssh-issues.rst
- source/system-administrators/activities/kubernetes/simple-kubernetes-deployment.rst
[3.1] Add other OS needing pem option when generating keys #3719
> [3.1] Add other OS needing pem option when generating keys #3719

- source/site-administrators/engine/engine-saml2-configuration.rst
- source/site-administrators/engine/engine-site-security-guide.rst
https://github.com/craftercms/craftercms/issues/3993
@sumerjabri please merge for 3.1 too
> Improve SAML2 doc for engine

- source/site-administrators/studio/webdav-profiles-configuration.rst
The sample webdav.xml is correct one with 2 nested <webdav> tags.
> Add missing nested <webdav> tags

- source/developers/projects/engine/index.rst
- source/developers/projects/engine/javascript-libraries.rst
Add list of Crafter CMS JavaScript libraries #4014
> Add list of Crafter CMS JavaScript libraries #4014

- source/developers/content-modeling.rst
- source/developers/index.rst
- source/developers/projects/engine/index.rst
- source/includes/scripts-templates-security.rst
- source/site-administrators/index.rst
- source/system-administrators/index.rst
Add engine sandbox configuration  to developer, site admin and system admin sections #4053
> Add engine sandbox configuration #4053

- source/site-administrators/engine/engine-saml2-configuration.rst
https://github.com/craftercms/craftercms/issues/3993
> Add notes about passwords for SAML2

- source/system-administrators/requirements-supported-platforms.rst
> Update supported java version

- source/system-administrators/activities/installing-and-verifying-prerequisites.rst
Update libncurses5 requirement
> Update libncurses5 requirement

- source/developers/in-context-editing-ftl.rst
Add note for some guidelines for drop zones in ftl
> Add note for some guidelines for drop zones in ftl

- source/system-administrators/upgrade/index.rst
Add note to shutdown Crafter before upgrading
> Add note to shutdown Crafter before upgrading

- source/system-administrators/activities/installing-and-verifying-prerequisites.rst
Update how to install libncurses5
> Update how to install libncurses5

- source/site-administrators/engine/engine-saml2-configuration.rst
https://github.com/craftersoftware/craftercms/issues/111, https://github.com/craftersoftware/craftercms/issues/104
> Update SAML2 configuration for engine

- source/developers/cook-books/marketplace/create-plugins.rst
- source/developers/plugins/blueprints.rst
Add links to marketplace from blueprint article
> Add links to marketplace from blueprint article

- source/system-administrators/deployer/processors-guide.rst
Add location of output of file output processor in processors guide
> Add location of output of file output processor in processors guide

- source/security/security-policies.rst
- source/system-administrators/activities/authoring/authoring-env-performance-tuning.rst
- source/system-administrators/activities/delivery/delivery-env-performance-tuning.rst
- source/system-administrators/activities/installing.rst
- source/system-administrators/activities/security/security-change-defaults.rst
Add list of default values to change to secure install
> Add list of default values to change to secure install

- source/site-administrators/engine/engine-multi-target-configuration.rst
Fix error in example config-list
> Fix error in example config-list

- source/system-administrators/activities/security/configure-studio-saml.rst
> Update Studio SAML #4127

- source/system-administrators/studio/studio-configuration-overrides.rst
Update Studio config overrides - Add new ES properties
> Update Studio config overrides - Add new ES properties

- source/site-administrators/engine/engine-saml2-configuration.rst
> Fixed Engine SAML 2 doc

- source/system-administrators/deployer/processors-guide.rst
Update deployer processors with new properties and processors
> Update deployer processors with new properties and processors

- source/developers/cook-books/box/use-box-to-store-assets.rst
- source/site-administrators/studio/box-profiles-configuration.rst
Update box profiles configuration documentation
Fix indentation of code-blocks
> Update box profiles configuration documentation

- source/system-administrators/upgrade/index.rst
- source/system-administrators/upgrade/upgrading-to-craftercms-3-0-x.rst
Add instructions for upgrading from 2.5.x to 3.0.x
> Add instructions for upgrading from 2.5.x to 3.0.x

- source/system-administrators/activities/autoclustering-with-studio.rst
https://github.com/craftersoftware/craftercms/issues/140
Please also merge for 3.1.x
> Update autocluster docs

- source/system-administrators/activities/delivery/setup-serverless-delivery.rst
- source/system-administrators/studio/studio-configuration-overrides.rst
Update serverless delivery #4174
Update serverless delivery properties studio-config-override
> Update serverless delivery #4174

- source/system-administrators/activities/delivery/setup-serverless-delivery.rst
- source/system-administrators/studio/studio-configuration-overrides.rst
Update serverless delivery guide for 3.1.x #4174
Update serverless delivery properties studio-config-override
> Update serverless delivery guide for 3.1.x #4174

- source/system-administrators/upgrade/docker/config/config-changes-3.1.7-to-3.1.8.rst
- source/system-administrators/upgrade/docker/config/index.rst
> Added Docker config changes from 3.1.7 to 3.1.8

- source/craftercms_sphinx_theme/layout.html
- ui/craftercms-sphinx-theme/src/sphinx/layout.html
Update layout.html to fix broken search result links when using the latest version of sphinx to build
> Update layout.html to fix broken search result links

- source/developers/projects/deployer/api/monitoring/status.rst
Fix typo in deployer monitoring status
> Fix typo in deployer monitoring status

- source/system-administrators/activities/delivery/setup-serverless-delivery.rst
- source/system-administrators/studio/studio-configuration-overrides.rst
Rollback serverless delivery properties changes #4174
> Rollback serverless delivery properties changes #4174

- source/developers/cook-books/active-cache/cache-a-restful-response.rst
Add how to enable active cache [3.1] #4210
> Add how to enable active cache [3.1] #4210

- source/acknowledgements/index.rst
Update OSS acknowledgements for 3.1
> Update OSS acknowledgements for 3.1

- source/developers/cook-books/active-cache/cache-a-restful-response.rst
Add how to enable active cache #4210
> Add how to enable active cache #4210

- source/developers/remote-assets.rst
Clarify remote assets controller is a Crafter Engine feature
> Clarify remote assets controller is a Crafter Engine feature

- source/developers/projects/craftercms/index.rst
- source/system-administrators/activities/security/security-change-defaults.rst
- source/system-administrators/studio/studio-configuration-overrides.rst
Add new salt and key variables #4178
> Add new salt and key variables #4178

- source/developers/projects/craftercms/index.rst
- source/system-administrators/activities/security/security-change-defaults.rst
- source/system-administrators/studio/studio-configuration-overrides.rst
[3.1] Add new salt and key variables #4178
> [3.1] Add new salt and key variables #4178

- source/system-administrators/activities/security/configure-studio-saml.rst
[master] Update how to enable Studio SAML
> [master] Update how to enable Studio SAML

- source/system-administrators/activities/security/configure-studio-saml.rst
[3.1] Update how to enable Studio SAML
> [3.1] Update how to enable Studio SAML

- source/system-administrators/requirements-supported-platforms.rst
[3.1] Update version requirement for macOS #4225
> [3.1] Update version requirement for macOS #4225

- source/system-administrators/requirements-supported-platforms.rst
[master] Update version requirement for macOS #4225
> [master] Update version requirement for macOS #4225

- source/system-administrators/activities/security/security-change-defaults.rst
Add missing spaces in code-block in changing defaults for security
> Add missing spaces in code-block in changing defaults for security

- source/site-administrators/engine/engine-site-configuration.rst
- source/site-administrators/engine/engine-site-security-guide.rst
Add note for url in urlRestrictions
> [3.1] Add note for url in urlRestrictions

- source/site-administrators/engine/engine-site-configuration.rst
- source/site-administrators/engine/engine-site-security-guide.rst
Update version requirement for macOS #4225
> [master] Add note for url in urlRestrictions

- source/acknowledgements/index.rst
Update oss acknowledgments to use search.maven.org
> Update oss acknowledgements to use search.maven.org

- source/system-administrators/activities/security/configure-ldap.rst
Update ldap configuration listed
> [master] Update ldap configuration listed

- source/system-administrators/activities/security/configure-ldap.rst
Update the ldap configuration listed
> [3.1] Update the ldap configuration listed

- source/site-administrators/engine/engine-headers-based-authentication.rst
Update example listed in header.ftl
> [3.1] Update example listed in header.ftl
