source/system-administrators/prod-environment/configure-studio-with-alfresco.rst

Many alfresco installations have timeout issues because of alfresco's ticket policy.  This document update is intended to combat this common problem

adding alfresco timeout to instructions

---

source/developers/content-modeling.rst
source/developers/extending-studio/build-a-data-source.rst
source/developers/extending-studio/form-engine-control.rst

Made form controls and data sources into components and referenced them from Content Modeling article and the Build Control/Build Source articles for ease of access.

Cross Referencing Controls and Sources

---

source/developers/projects/studio/api/group-management/get-groups.rst
source/developers/projects/studio/api/index.rst
source/developers/projects/studio/api/user-management/get-user.rst
source/developers/projects/studio/api/user-management/get-users.rst

Updated user management API to return only group_name and removed all
references to group_id. Added group information to the API call
get-users-per-site. Added get groups API.

User and Group Management API

---

source/developers/projects/craftercms/index.rst

Update description that gradle task property moduleName accepts multiple modules.

Update description of gradle task property moduleName

---

source/system-administrators/reindexing-content.rst

* Curl calls now indicate the name of the module (Solr or Deployer) (fix for craftercms/craftercms#1775)

Fix for 1775:

---

source/_static/custom.css
source/_static/custom.scss
source/conf.py
source/release-notes/index.rst

Restructure release notes #1845 
Update css files to make updates for admonitions (make admonitions pop) and toc (make toc entries distinguishable) like in 3.0

Update css files and restructure release notes

---

source/system-administrators/activities/setup-site-for-delivery.rst

* Now the note in the setup delivery doc describes what to do in UnknownHostKey errors.
Ticket craftercms/craftercms#1972

Fixed note in setup delivery site doc:

---

source/system-administrators/upgrade/upgrading-to-craftercms-3-0.rst

* Added a little more explanation on how to export a Crafter 2.5 site (ticket craftercms/craftercms#1994).

 Fixed upgrade doc:

---

source/developers/cook-books/content-queries/basic-query-mechanics.rst

This PR fixes a syntax issue with the groovy solr query. The single/double quote fails to parse on crafter 3.0.20. Secondly, content-type queries are more suitable for filter queries in solr rather than queries located in the main query string.

Syntax fix + style fix for Solr query example

---

source/includes/setup-ssh-keys.rst
source/system-administrators/activities/debugging-ssh-issues.rst
source/system-administrators/activities/troubleshooting.rst
source/system-administrators/index.rst
source/system-administrators/studio/create-site-with-link-to-remote-repo.rst

Add note that passphrase is not supported for ssh key for 3.0

Add note that passphrase is not supported for ssh key for 3.0

---

source/system-administrators/activities/delivery/configure-apache-vhost.rst

This is to follow the same ports as the file crafter-setenv.sh for the delivery

set the default port for ajp to 9009 for delivery

---

source/developers/projects/studio/api/site/create-site.rst

In 3.0 the blueprint parameter is `empty`

Revert change of blueprint name to empty

---

source/developers/cook-books/content-queries/basic-query-mechanics.rst
source/includes/global-groovy-variables.rst

Fix link redirects to the javadoc http://javadoc.craftercms.org/3.1.0/search/org/craftercms/search/elasticsearch/ElasticsearchWrapper.html

Fix ElasticsearchWrapper javadoc link

---

source/includes/setup-ssh-keys.rst
source/system-administrators/activities/debugging-ssh-issues.rst
source/system-administrators/activities/delivery/setup-site-for-delivery.rst
source/system-administrators/activities/kubernetes/simple-kubernetes-deployment.rst
source/system-administrators/studio/create-site-with-link-to-remote-repo.rst

Add note for macOS 10.14 or OpenSSH 7.8 and up users to use -m PEM when creating ssh keys #3719

Add note for macOS 10.14 or OpenSSH 7.8 users to use -m PEM when creating ssh keys #3719

---

source/developers/projects/engine/api/site/context/status.rst

Fix warning of duplicate label for `crafter-engine-api-site-context-id`

Fix warning of duplicate label

---

source/developers/projects/craftercms/index.rst

If the user previously built Crafter 2.5.x, then pull the latest 3.1, a clean rebuild will not resolve issues due to differences between the two versions of Crafter. Most of the time, startup will produce errors. The best solution is to delete both environment folders "crafter-authoring" and "crafter-delivery".

Add Note about the 'clean' gradle command.

---

source/system-administrators/activities/autoclustering-with-studio.rst

The Auto-Clustering example uses `CLUSTER_NAME=studio_db_cluster` update the value in the Studio Arbiter example to match.

Update CLUSTER_NAME variable in arbiter to match cluster example

---

source/developers/remote-assets.rst

The ability to reference remote assets is a feature provided by Crafter Delivery (not Studio). Remote asset data source is a Crafter Studio feature that helps create the URL patterns mentioned here. It is the remote assets controller of Crafter Delivery that parses that URL pattern and provides the access to browsers.

Clarify remote assets controller is a Crafter Delivery feature

---

source/site-administrators/engine/engine-crafter-profile-configuration.rst
source/system-administrators/profile/admin/guides/access_tokens.rst

Add notes to use site name for tenant in Engine Crafter Profile configuration

[3.1] Add notes to use site name for tenant in Engine Crafter Profile configuration

---

source/developers/content-modeling.rst

In Groovy context, contentModel is a SiteItem. Statement "contentModel.events = events" will cause this exception:
groovy.lang.MissingPropertyException: No such property: events for class: org.craftercms.engine.model.DefaultSiteItem

Controller should add new objects to templateModel

---

source/developers/content-modeling.rst

Add note to remove the Studio UI auto-added postfix when using `key` or `value` variable names like in the Taxonomy content type

[master] Add note for using key or value variable names

---

source/developers/content-modeling.rst

Add note to remove the Studio UI auto-added postfix when using `key` or `value` variable names like in the Taxonomy content type

[3.1] Add note for using key or value variable names

---

source/developers/projects/engine/api/groovy-api.rst

Fix typo in sitemap.groovy example

[3.1] Fix typo in sitemap.groovy example

---

source/site-administrators/studio/rte2-setup.rst

Specified that a setup tag is required (you can't just add another ID block), and specify that a space is the required separator character between items in the plugins and toolbarItems lists.

Update docs to clarify RTE toolbar config details

---

source/system-administrators/upgrade/docker/config/config-changes-3.1.12-to-3.1.13.rst

Fix typo in version numbers for docker config changes from 3.1.12 to 3.1.13

Fix typo in version numbers for docker config changes from 3.1.12 to 3.1.13

---

source/site-administrators/engine/engine-headers-based-authentication.rst

Push updates from 3.1 for custom user attribute configuration in engine headers based auth

Push updates from 3.1 for custom user attribute configuration in engine headers based auth

---

source/developers/projects/search/api/index.rst

Fix warning for spacing and over line in crafter search api

Fix warning for spacing in crafter search api

---

source/developers/projects/studio/api/publish/commits.rst

Due to the update from 3.1.6 to 3.1.7: https://docs.craftercms.org/en/3.1/release-notes/index.html?#crafter-cms-3-1-7
> The environment-config.xml configuration has been removed
> The following tags from the environment-config.xml file has been removed and staging and live are now used as defaults for the repository branch name for publishing targets:
> 
> The tags below from “environment-config.xml” no longer exist, “staging” and “live” are now used as default publishing targets¶
```
<open-sidebar />
<publishing-targets>
<target>
<repo-branch-name />
<display-label />
</target>
</publishing-targets>
```
The API call with "Live" is no longer work as we don't have `<display-label>Live</display-label>` anymore. For that reason, using `live` in the sample to make it consistent.

[3.1] Update sample commits api to use environment live instead of Live

---

source/developers/plugins/site-plugins.rst

Site-Plugin: Fixed broken link in google analytics plugin "head.ftl" example.

Fix broken link in google-analytics site-plugin documentation

---

source/developers/cook-books/how-tos/working-with-crafter-studios-api.rst

The note about Spring with the curl example to `http://localhost:8080/studio/api/1/services/api/1/security/login.json` is not valid in version 4.x

Remove note that is only valid in 3.x from 4.x docs

---

source/developers/cook-books/how-tos/working-with-crafter-studios-api.rst
source/system-administrators/devcontentops-toolkit/add-environment.rst
source/system-administrators/devcontentops-toolkit/index.rst

Add note to enable http basic auth flag when using username/password for authentication in the `add-environment` command of `crafter-cli`

Add note to enable http basic auth flag

---

source/developers/plugins/blueprints.rst
source/developers/plugins/plugin-descriptor.rst
source/developers/plugins/site-plugins.rst

Remove build and searchEngine in plugin descriptor docs https://github.com/craftercms/craftercms/issues/5224
Fix description for `YourPluginFilesAndFolder`

Remove build and searchEngine in descriptor #5224

---

source/developers/cook-books/active-cache/cache-a-restful-response.rst
source/site-administrators/engine/engine-project-configuration.rst

Update cache and CORS behavior in preview mode  https://github.com/craftercms/craftercms/issues/5737

Update cache and CORS behavior in preview mode #5737

---

source/developers/extensions/index.rst

Fix link to plugin host page in extensions index

Fix link to plugin host page in extensions index

---

source/developers/projects/engine/api/site/graphql/get.rst

Changed `GET .../api/1/site/graphql.json?query={page_article{items{title}}}` for `GET .../api/1/site/graphql.json?query={page_article{items{title_t}}}` since the GraphQL GET query example was failing with an error:
```
{
"errors": [
{
"message": "Validation error of type FieldUndefined: Field 'title' in type 'page_article' is undefined @ 'page_article/items/title'",
"locations": [
{
"line": 1,
"column": 21
}
],
"extensions": {
"classification": "ValidationError"
}
}
]
}
```

Fix GraphQL GET Query Example

---

source/developers/plugins/studio-plugins.rst
source/developers/plugins/studio/form-control-plugins.rst
source/developers/plugins/studio/form-data-source-plugins.rst

Fix broken link and update links to be anonymous (by using two trailing underscores)
According to: http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#anonymous-hyperlinks
```
With a single trailing underscore, the reference is named and the same target URI may be referred to again. With two trailing underscores, the reference and target are both anonymous, and the target cannot be referred to again. These are "one-off" hyperlinks.
```

[3.1] Fix broken link and update link to be anonymous

---

source/conf.py

Increase the navigation depth in sidebar. The default depth is 4 when not specified.

Increase the navigation depth in sidebar

---

source/developers/projects/engine/api/templating-api.rst

Add escaping html and scripts section in templating API  https://github.com/craftersoftware/craftercms/issues/795

[4.0] Add escaping html and scripts section in templating API #795

---

source/reference/modules/studio/configuration/index.rst

The >- notation is not commonly used but the following line requires an indent for the syntax to be correct.

Trivial YAML spacing change

---

source/reference/modules/studio/security.rst

Add some more description to access token environment variables https://github.com/craftercms/craftercms/issues/6656

Add some more description to access token environment variables #6656
